package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedCommentController;
import pt.isep.enorm.ref.service.CommentService;

@RestController
@RequestMapping(value = "/api")
public class CommentController extends GeneratedCommentController {
  public CommentController(CommentService templateService) {
    super(templateService);
  }
}
