package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedLikeOnCommentController;
import pt.isep.enorm.ref.service.LikeOnCommentService;

@RestController
@RequestMapping(value = "/api")
public class LikeOnCommentController extends GeneratedLikeOnCommentController {
  public LikeOnCommentController(LikeOnCommentService templateService) {
    super(templateService);
  }
}
