package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedReportOnCommentController;
import pt.isep.enorm.ref.service.ReportOnCommentService;

@RestController
@RequestMapping(value = "/api")
public class ReportOnCommentController extends GeneratedReportOnCommentController {
  public ReportOnCommentController(ReportOnCommentService templateService) {
    super(templateService);
  }
}
