package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedVideoController;
import pt.isep.enorm.ref.service.VideoService;

@RestController
@RequestMapping(value = "/api")
public class VideoController extends GeneratedVideoController {
  public VideoController(VideoService templateService) {
    super(templateService);
  }
}
