/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.enorm.refdsl.ide.contentassist.antlr.internal.InternalRefDslParser;
import pt.isep.enorm.refdsl.services.RefDslGrammarAccess;

public class RefDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RefDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RefDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getUserKindAccess().getAlternatives(), "rule__UserKind__Alternatives");
			builder.put(grammarAccess.getContextKindAccess().getAlternatives(), "rule__ContextKind__Alternatives");
			builder.put(grammarAccess.getPrimitiveTypeAccess().getAlternatives(), "rule__PrimitiveType__Alternatives");
			builder.put(grammarAccess.getFeedbackKindAccess().getAlternatives(), "rule__FeedbackKind__Alternatives");
			builder.put(grammarAccess.getFeedbackSubjectScopeAccess().getAlternatives(), "rule__FeedbackSubjectScope__Alternatives");
			builder.put(grammarAccess.getFeedbackPolarityAccess().getAlternatives(), "rule__FeedbackPolarity__Alternatives");
			builder.put(grammarAccess.getFeedbackStatusAccess().getAlternatives(), "rule__FeedbackStatus__Alternatives");
			builder.put(grammarAccess.getVerificationRequirementAccess().getAlternatives(), "rule__VerificationRequirement__Alternatives");
			builder.put(grammarAccess.getValidationKindAccess().getAlternatives(), "rule__ValidationKind__Alternatives");
			builder.put(grammarAccess.getRuleSeverityAccess().getAlternatives(), "rule__RuleSeverity__Alternatives");
			builder.put(grammarAccess.getModerationModeAccess().getAlternatives(), "rule__ModerationMode__Alternatives");
			builder.put(grammarAccess.getModerationDecisionAccess().getAlternatives(), "rule__ModerationDecision__Alternatives");
			builder.put(grammarAccess.getActionKindAccess().getAlternatives(), "rule__ActionKind__Alternatives");
			builder.put(grammarAccess.getTriggerEventAccess().getAlternatives(), "rule__TriggerEvent__Alternatives");
			builder.put(grammarAccess.getConditionOperatorAccess().getAlternatives(), "rule__ConditionOperator__Alternatives");
			builder.put(grammarAccess.getActionResultKindAccess().getAlternatives(), "rule__ActionResultKind__Alternatives");
			builder.put(grammarAccess.getSortCriterionAccess().getAlternatives(), "rule__SortCriterion__Alternatives");
			builder.put(grammarAccess.getSortDirectionAccess().getAlternatives(), "rule__SortDirection__Alternatives");
			builder.put(grammarAccess.getRefModelAccess().getGroup(), "rule__RefModel__Group__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_2(), "rule__RefModel__Group_2__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_4(), "rule__RefModel__Group_4__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_4_3(), "rule__RefModel__Group_4_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_5(), "rule__RefModel__Group_5__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_5_3(), "rule__RefModel__Group_5_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_6(), "rule__RefModel__Group_6__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_6_3(), "rule__RefModel__Group_6_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_7(), "rule__RefModel__Group_7__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_7_3(), "rule__RefModel__Group_7_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_8(), "rule__RefModel__Group_8__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_8_3(), "rule__RefModel__Group_8_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_9(), "rule__RefModel__Group_9__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_9_3(), "rule__RefModel__Group_9_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_10(), "rule__RefModel__Group_10__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_10_3(), "rule__RefModel__Group_10_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_11(), "rule__RefModel__Group_11__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_11_3(), "rule__RefModel__Group_11_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_12(), "rule__RefModel__Group_12__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_12_3(), "rule__RefModel__Group_12_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_13(), "rule__RefModel__Group_13__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_13_3(), "rule__RefModel__Group_13_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_14(), "rule__RefModel__Group_14__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_14_3(), "rule__RefModel__Group_14_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_15(), "rule__RefModel__Group_15__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_15_3(), "rule__RefModel__Group_15_3__0");
			builder.put(grammarAccess.getUserTypeAccess().getGroup(), "rule__UserType__Group__0");
			builder.put(grammarAccess.getUserTypeAccess().getGroup_4(), "rule__UserType__Group_4__0");
			builder.put(grammarAccess.getUserTypeAccess().getGroup_4_3(), "rule__UserType__Group_4_3__0");
			builder.put(grammarAccess.getContextTypeAccess().getGroup(), "rule__ContextType__Group__0");
			builder.put(grammarAccess.getContextTypeAccess().getGroup_4(), "rule__ContextType__Group_4__0");
			builder.put(grammarAccess.getContextTypeAccess().getGroup_4_3(), "rule__ContextType__Group_4_3__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup(), "rule__ResourceType__Group__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_2(), "rule__ResourceType__Group_2__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_3(), "rule__ResourceType__Group_3__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_3_3(), "rule__ResourceType__Group_3_3__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_5(), "rule__ResourceType__Group_5__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_5_3(), "rule__ResourceType__Group_5_3__0");
			builder.put(grammarAccess.getResourceRelationAccess().getGroup(), "rule__ResourceRelation__Group__0");
			builder.put(grammarAccess.getResourceRelationAccess().getGroup_6(), "rule__ResourceRelation__Group_6__0");
			builder.put(grammarAccess.getResourceRelationAccess().getGroup_7(), "rule__ResourceRelation__Group_7__0");
			builder.put(grammarAccess.getResourceRelationAccess().getGroup_8(), "rule__ResourceRelation__Group_8__0");
			builder.put(grammarAccess.getResourceRelationAccess().getGroup_9(), "rule__ResourceRelation__Group_9__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_0(), "rule__Attribute__Group_0__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_1(), "rule__Attribute__Group_1__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup(), "rule__FeedbackType__Group__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_4(), "rule__FeedbackType__Group_4__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_5(), "rule__FeedbackType__Group_5__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_6(), "rule__FeedbackType__Group_6__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_7(), "rule__FeedbackType__Group_7__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_8(), "rule__FeedbackType__Group_8__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_9(), "rule__FeedbackType__Group_9__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup(), "rule__FeedbackDefinition__Group__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_4(), "rule__FeedbackDefinition__Group_4__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_5(), "rule__FeedbackDefinition__Group_5__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_6(), "rule__FeedbackDefinition__Group_6__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_9(), "rule__FeedbackDefinition__Group_9__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_10(), "rule__FeedbackDefinition__Group_10__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_11(), "rule__FeedbackDefinition__Group_11__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_12(), "rule__FeedbackDefinition__Group_12__0");
			builder.put(grammarAccess.getFeedbackPolicyAccess().getGroup(), "rule__FeedbackPolicy__Group__0");
			builder.put(grammarAccess.getFeedbackPolicyAccess().getGroup_1(), "rule__FeedbackPolicy__Group_1__0");
			builder.put(grammarAccess.getRatingPolicyAccess().getGroup(), "rule__RatingPolicy__Group__0");
			builder.put(grammarAccess.getRatingPolicyAccess().getGroup_5(), "rule__RatingPolicy__Group_5__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup(), "rule__ValidationRule__Group__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_1(), "rule__ValidationRule__Group_1__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_4(), "rule__ValidationRule__Group_4__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_5(), "rule__ValidationRule__Group_5__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_6(), "rule__ValidationRule__Group_6__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_7(), "rule__ValidationRule__Group_7__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_8(), "rule__ValidationRule__Group_8__0");
			builder.put(grammarAccess.getModerationPolicyAccess().getGroup(), "rule__ModerationPolicy__Group__0");
			builder.put(grammarAccess.getModerationPolicyAccess().getGroup_1(), "rule__ModerationPolicy__Group_1__0");
			builder.put(grammarAccess.getModerationPolicyAccess().getGroup_4(), "rule__ModerationPolicy__Group_4__0");
			builder.put(grammarAccess.getModerationPolicyAccess().getGroup_5(), "rule__ModerationPolicy__Group_5__0");
			builder.put(grammarAccess.getModerationPolicyAccess().getGroup_12(), "rule__ModerationPolicy__Group_12__0");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getGroup(), "rule__AuthorizationRule__Group__0");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getGroup_1(), "rule__AuthorizationRule__Group_1__0");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getGroup_6(), "rule__AuthorizationRule__Group_6__0");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getGroup_9(), "rule__AuthorizationRule__Group_9__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup(), "rule__AutomationRule__Group__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_4(), "rule__AutomationRule__Group_4__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_5(), "rule__AutomationRule__Group_5__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_10(), "rule__AutomationRule__Group_10__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_10_3(), "rule__AutomationRule__Group_10_3__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_14(), "rule__AutomationRule__Group_14__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_19(), "rule__AutomationRule__Group_19__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_6(), "rule__Condition__Group_6__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_6_3(), "rule__Condition__Group_6_3__0");
			builder.put(grammarAccess.getConditionValueAccess().getGroup(), "rule__ConditionValue__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
			builder.put(grammarAccess.getVerificationPolicyAccess().getGroup(), "rule__VerificationPolicy__Group__0");
			builder.put(grammarAccess.getVerificationPolicyAccess().getGroup_1(), "rule__VerificationPolicy__Group_1__0");
			builder.put(grammarAccess.getSortingPolicyAccess().getGroup(), "rule__SortingPolicy__Group__0");
			builder.put(grammarAccess.getSortingPolicyAccess().getGroup_6(), "rule__SortingPolicy__Group_6__0");
			builder.put(grammarAccess.getSortingPolicyAccess().getGroup_7(), "rule__SortingPolicy__Group_7__0");
			builder.put(grammarAccess.getSortingPolicyAccess().getGroup_8(), "rule__SortingPolicy__Group_8__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_1(), "rule__EDouble__Group_1__0");
			builder.put(grammarAccess.getRefModelAccess().getNameAssignment_1(), "rule__RefModel__NameAssignment_1");
			builder.put(grammarAccess.getRefModelAccess().getVersionAssignment_2_1(), "rule__RefModel__VersionAssignment_2_1");
			builder.put(grammarAccess.getRefModelAccess().getUserTypesAssignment_4_2(), "rule__RefModel__UserTypesAssignment_4_2");
			builder.put(grammarAccess.getRefModelAccess().getUserTypesAssignment_4_3_1(), "rule__RefModel__UserTypesAssignment_4_3_1");
			builder.put(grammarAccess.getRefModelAccess().getResourceTypesAssignment_5_2(), "rule__RefModel__ResourceTypesAssignment_5_2");
			builder.put(grammarAccess.getRefModelAccess().getResourceTypesAssignment_5_3_1(), "rule__RefModel__ResourceTypesAssignment_5_3_1");
			builder.put(grammarAccess.getRefModelAccess().getContextTypesAssignment_6_2(), "rule__RefModel__ContextTypesAssignment_6_2");
			builder.put(grammarAccess.getRefModelAccess().getContextTypesAssignment_6_3_1(), "rule__RefModel__ContextTypesAssignment_6_3_1");
			builder.put(grammarAccess.getRefModelAccess().getResourceRelationsAssignment_7_2(), "rule__RefModel__ResourceRelationsAssignment_7_2");
			builder.put(grammarAccess.getRefModelAccess().getResourceRelationsAssignment_7_3_1(), "rule__RefModel__ResourceRelationsAssignment_7_3_1");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackTypesAssignment_8_2(), "rule__RefModel__FeedbackTypesAssignment_8_2");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackTypesAssignment_8_3_1(), "rule__RefModel__FeedbackTypesAssignment_8_3_1");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackDefinitionsAssignment_9_2(), "rule__RefModel__FeedbackDefinitionsAssignment_9_2");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackDefinitionsAssignment_9_3_1(), "rule__RefModel__FeedbackDefinitionsAssignment_9_3_1");
			builder.put(grammarAccess.getRefModelAccess().getAuthorizationRulesAssignment_10_2(), "rule__RefModel__AuthorizationRulesAssignment_10_2");
			builder.put(grammarAccess.getRefModelAccess().getAuthorizationRulesAssignment_10_3_1(), "rule__RefModel__AuthorizationRulesAssignment_10_3_1");
			builder.put(grammarAccess.getRefModelAccess().getValidationRulesAssignment_11_2(), "rule__RefModel__ValidationRulesAssignment_11_2");
			builder.put(grammarAccess.getRefModelAccess().getValidationRulesAssignment_11_3_1(), "rule__RefModel__ValidationRulesAssignment_11_3_1");
			builder.put(grammarAccess.getRefModelAccess().getModerationPoliciesAssignment_12_2(), "rule__RefModel__ModerationPoliciesAssignment_12_2");
			builder.put(grammarAccess.getRefModelAccess().getModerationPoliciesAssignment_12_3_1(), "rule__RefModel__ModerationPoliciesAssignment_12_3_1");
			builder.put(grammarAccess.getRefModelAccess().getAutomationRulesAssignment_13_2(), "rule__RefModel__AutomationRulesAssignment_13_2");
			builder.put(grammarAccess.getRefModelAccess().getAutomationRulesAssignment_13_3_1(), "rule__RefModel__AutomationRulesAssignment_13_3_1");
			builder.put(grammarAccess.getRefModelAccess().getVerificationPoliciesAssignment_14_2(), "rule__RefModel__VerificationPoliciesAssignment_14_2");
			builder.put(grammarAccess.getRefModelAccess().getVerificationPoliciesAssignment_14_3_1(), "rule__RefModel__VerificationPoliciesAssignment_14_3_1");
			builder.put(grammarAccess.getRefModelAccess().getSortingPoliciesAssignment_15_2(), "rule__RefModel__SortingPoliciesAssignment_15_2");
			builder.put(grammarAccess.getRefModelAccess().getSortingPoliciesAssignment_15_3_1(), "rule__RefModel__SortingPoliciesAssignment_15_3_1");
			builder.put(grammarAccess.getUserTypeAccess().getNameAssignment_1(), "rule__UserType__NameAssignment_1");
			builder.put(grammarAccess.getUserTypeAccess().getKindAssignment_3(), "rule__UserType__KindAssignment_3");
			builder.put(grammarAccess.getUserTypeAccess().getSuperTypesAssignment_4_2(), "rule__UserType__SuperTypesAssignment_4_2");
			builder.put(grammarAccess.getUserTypeAccess().getSuperTypesAssignment_4_3_1(), "rule__UserType__SuperTypesAssignment_4_3_1");
			builder.put(grammarAccess.getContextTypeAccess().getNameAssignment_1(), "rule__ContextType__NameAssignment_1");
			builder.put(grammarAccess.getContextTypeAccess().getKindAssignment_3(), "rule__ContextType__KindAssignment_3");
			builder.put(grammarAccess.getContextTypeAccess().getContainsAssignment_4_2(), "rule__ContextType__ContainsAssignment_4_2");
			builder.put(grammarAccess.getContextTypeAccess().getContainsAssignment_4_3_1(), "rule__ContextType__ContainsAssignment_4_3_1");
			builder.put(grammarAccess.getResourceTypeAccess().getNameAssignment_1(), "rule__ResourceType__NameAssignment_1");
			builder.put(grammarAccess.getResourceTypeAccess().getSupportsMediaAssignment_2_1(), "rule__ResourceType__SupportsMediaAssignment_2_1");
			builder.put(grammarAccess.getResourceTypeAccess().getSuperTypesAssignment_3_2(), "rule__ResourceType__SuperTypesAssignment_3_2");
			builder.put(grammarAccess.getResourceTypeAccess().getSuperTypesAssignment_3_3_1(), "rule__ResourceType__SuperTypesAssignment_3_3_1");
			builder.put(grammarAccess.getResourceTypeAccess().getAttributesAssignment_5_2(), "rule__ResourceType__AttributesAssignment_5_2");
			builder.put(grammarAccess.getResourceTypeAccess().getAttributesAssignment_5_3_1(), "rule__ResourceType__AttributesAssignment_5_3_1");
			builder.put(grammarAccess.getResourceRelationAccess().getNameAssignment_1(), "rule__ResourceRelation__NameAssignment_1");
			builder.put(grammarAccess.getResourceRelationAccess().getSourceAssignment_3(), "rule__ResourceRelation__SourceAssignment_3");
			builder.put(grammarAccess.getResourceRelationAccess().getTargetAssignment_5(), "rule__ResourceRelation__TargetAssignment_5");
			builder.put(grammarAccess.getResourceRelationAccess().getSourceCardinalityAssignment_6_1(), "rule__ResourceRelation__SourceCardinalityAssignment_6_1");
			builder.put(grammarAccess.getResourceRelationAccess().getTargetCardinalityAssignment_7_1(), "rule__ResourceRelation__TargetCardinalityAssignment_7_1");
			builder.put(grammarAccess.getResourceRelationAccess().getContainmentAssignment_8_1(), "rule__ResourceRelation__ContainmentAssignment_8_1");
			builder.put(grammarAccess.getResourceRelationAccess().getRecursiveAssignment_9_1(), "rule__ResourceRelation__RecursiveAssignment_9_1");
			builder.put(grammarAccess.getAttributeAccess().getRequiredAssignment_0_1(), "rule__Attribute__RequiredAssignment_0_1");
			builder.put(grammarAccess.getAttributeAccess().getMultiValuedAssignment_1_1(), "rule__Attribute__MultiValuedAssignment_1_1");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_3(), "rule__Attribute__NameAssignment_3");
			builder.put(grammarAccess.getAttributeAccess().getTypeAssignment_5(), "rule__Attribute__TypeAssignment_5");
			builder.put(grammarAccess.getFeedbackTypeAccess().getNameAssignment_1(), "rule__FeedbackType__NameAssignment_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getKindAssignment_3(), "rule__FeedbackType__KindAssignment_3");
			builder.put(grammarAccess.getFeedbackTypeAccess().getSubjectScopeAssignment_4_1(), "rule__FeedbackType__SubjectScopeAssignment_4_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getHasRatingAssignment_5_1(), "rule__FeedbackType__HasRatingAssignment_5_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getRecursiveAssignment_6_1(), "rule__FeedbackType__RecursiveAssignment_6_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getAllowsTextAssignment_7_1(), "rule__FeedbackType__AllowsTextAssignment_7_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getAllowsMediaAssignment_8_1(), "rule__FeedbackType__AllowsMediaAssignment_8_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getPolarityAssignment_9_1(), "rule__FeedbackType__PolarityAssignment_9_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getNameAssignment_1(), "rule__FeedbackDefinition__NameAssignment_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getTypeAssignment_3(), "rule__FeedbackDefinition__TypeAssignment_3");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getRequiresVerifiedContextAssignment_4_1(), "rule__FeedbackDefinition__RequiresVerifiedContextAssignment_4_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getVerificationRequirementAssignment_5_1(), "rule__FeedbackDefinition__VerificationRequirementAssignment_5_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getUniquePerAuthorTargetAssignment_6_1(), "rule__FeedbackDefinition__UniquePerAuthorTargetAssignment_6_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getAuthorAssignment_8(), "rule__FeedbackDefinition__AuthorAssignment_8");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getSubjectResourceAssignment_9_1(), "rule__FeedbackDefinition__SubjectResourceAssignment_9_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getSubjectFeedbackAssignment_10_1(), "rule__FeedbackDefinition__SubjectFeedbackAssignment_10_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getPolicyAssignment_11_1(), "rule__FeedbackDefinition__PolicyAssignment_11_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getRatingAssignment_12_1(), "rule__FeedbackDefinition__RatingAssignment_12_1");
			builder.put(grammarAccess.getFeedbackPolicyAccess().getStatusAssignment_1_1(), "rule__FeedbackPolicy__StatusAssignment_1_1");
			builder.put(grammarAccess.getRatingPolicyAccess().getMinValueAssignment_2(), "rule__RatingPolicy__MinValueAssignment_2");
			builder.put(grammarAccess.getRatingPolicyAccess().getMaxValueAssignment_4(), "rule__RatingPolicy__MaxValueAssignment_4");
			builder.put(grammarAccess.getRatingPolicyAccess().getStepAssignment_5_1(), "rule__RatingPolicy__StepAssignment_5_1");
			builder.put(grammarAccess.getValidationRuleAccess().getNameAssignment_1_1(), "rule__ValidationRule__NameAssignment_1_1");
			builder.put(grammarAccess.getValidationRuleAccess().getKindAssignment_3(), "rule__ValidationRule__KindAssignment_3");
			builder.put(grammarAccess.getValidationRuleAccess().getSeverityAssignment_4_1(), "rule__ValidationRule__SeverityAssignment_4_1");
			builder.put(grammarAccess.getValidationRuleAccess().getExpressionAssignment_5_1(), "rule__ValidationRule__ExpressionAssignment_5_1");
			builder.put(grammarAccess.getValidationRuleAccess().getImplementationIdAssignment_6_1(), "rule__ValidationRule__ImplementationIdAssignment_6_1");
			builder.put(grammarAccess.getValidationRuleAccess().getAppliesToResourceAssignment_7_1(), "rule__ValidationRule__AppliesToResourceAssignment_7_1");
			builder.put(grammarAccess.getValidationRuleAccess().getAppliesToFeedbackAssignment_8_1(), "rule__ValidationRule__AppliesToFeedbackAssignment_8_1");
			builder.put(grammarAccess.getValidationRuleAccess().getInvokedByAssignment_10(), "rule__ValidationRule__InvokedByAssignment_10");
			builder.put(grammarAccess.getModerationPolicyAccess().getNameAssignment_1_1(), "rule__ModerationPolicy__NameAssignment_1_1");
			builder.put(grammarAccess.getModerationPolicyAccess().getModeAssignment_3(), "rule__ModerationPolicy__ModeAssignment_3");
			builder.put(grammarAccess.getModerationPolicyAccess().getTriggerAssignment_4_1(), "rule__ModerationPolicy__TriggerAssignment_4_1");
			builder.put(grammarAccess.getModerationPolicyAccess().getDecisionAssignment_5_1(), "rule__ModerationPolicy__DecisionAssignment_5_1");
			builder.put(grammarAccess.getModerationPolicyAccess().getMonitorsResourceAssignment_7(), "rule__ModerationPolicy__MonitorsResourceAssignment_7");
			builder.put(grammarAccess.getModerationPolicyAccess().getMonitorsFeedbackAssignment_9(), "rule__ModerationPolicy__MonitorsFeedbackAssignment_9");
			builder.put(grammarAccess.getModerationPolicyAccess().getExecutedByAssignment_11(), "rule__ModerationPolicy__ExecutedByAssignment_11");
			builder.put(grammarAccess.getModerationPolicyAccess().getInContextAssignment_12_1(), "rule__ModerationPolicy__InContextAssignment_12_1");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getNameAssignment_1_1(), "rule__AuthorizationRule__NameAssignment_1_1");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getAllowedActionAssignment_3(), "rule__AuthorizationRule__AllowedActionAssignment_3");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getActorAssignment_5(), "rule__AuthorizationRule__ActorAssignment_5");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getContextAssignment_6_1(), "rule__AuthorizationRule__ContextAssignment_6_1");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getResourceTargetAssignment_8(), "rule__AuthorizationRule__ResourceTargetAssignment_8");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getFeedbackTargetAssignment_9_1(), "rule__AuthorizationRule__FeedbackTargetAssignment_9_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getNameAssignment_1(), "rule__AutomationRule__NameAssignment_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getTriggerAssignment_3(), "rule__AutomationRule__TriggerAssignment_3");
			builder.put(grammarAccess.getAutomationRuleAccess().getContextAssignment_4_1(), "rule__AutomationRule__ContextAssignment_4_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getInContextAssignment_5_1(), "rule__AutomationRule__InContextAssignment_5_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getOnFeedbackAssignment_7(), "rule__AutomationRule__OnFeedbackAssignment_7");
			builder.put(grammarAccess.getAutomationRuleAccess().getUsesAssignment_9(), "rule__AutomationRule__UsesAssignment_9");
			builder.put(grammarAccess.getAutomationRuleAccess().getInvokedValidationRulesAssignment_10_2(), "rule__AutomationRule__InvokedValidationRulesAssignment_10_2");
			builder.put(grammarAccess.getAutomationRuleAccess().getInvokedValidationRulesAssignment_10_3_1(), "rule__AutomationRule__InvokedValidationRulesAssignment_10_3_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getConditionsAssignment_13(), "rule__AutomationRule__ConditionsAssignment_13");
			builder.put(grammarAccess.getAutomationRuleAccess().getConditionsAssignment_14_1(), "rule__AutomationRule__ConditionsAssignment_14_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getActionsAssignment_18(), "rule__AutomationRule__ActionsAssignment_18");
			builder.put(grammarAccess.getAutomationRuleAccess().getActionsAssignment_19_1(), "rule__AutomationRule__ActionsAssignment_19_1");
			builder.put(grammarAccess.getConditionAccess().getNameAssignment_1(), "rule__Condition__NameAssignment_1");
			builder.put(grammarAccess.getConditionAccess().getOperatorAssignment_3(), "rule__Condition__OperatorAssignment_3");
			builder.put(grammarAccess.getConditionAccess().getAttributeAssignment_5(), "rule__Condition__AttributeAssignment_5");
			builder.put(grammarAccess.getConditionAccess().getChildrenAssignment_6_2(), "rule__Condition__ChildrenAssignment_6_2");
			builder.put(grammarAccess.getConditionAccess().getChildrenAssignment_6_3_1(), "rule__Condition__ChildrenAssignment_6_3_1");
			builder.put(grammarAccess.getConditionValueAccess().getValueAssignment_1(), "rule__ConditionValue__ValueAssignment_1");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
			builder.put(grammarAccess.getActionAccess().getKindAssignment_3(), "rule__Action__KindAssignment_3");
			builder.put(grammarAccess.getActionAccess().getMessageAssignment_4_1(), "rule__Action__MessageAssignment_4_1");
			builder.put(grammarAccess.getVerificationPolicyAccess().getNameAssignment_1_1(), "rule__VerificationPolicy__NameAssignment_1_1");
			builder.put(grammarAccess.getVerificationPolicyAccess().getModeAssignment_3(), "rule__VerificationPolicy__ModeAssignment_3");
			builder.put(grammarAccess.getVerificationPolicyAccess().getAppliesWhenAssignment_5(), "rule__VerificationPolicy__AppliesWhenAssignment_5");
			builder.put(grammarAccess.getVerificationPolicyAccess().getVerifiesAssignment_7(), "rule__VerificationPolicy__VerifiesAssignment_7");
			builder.put(grammarAccess.getSortingPolicyAccess().getNameAssignment_1(), "rule__SortingPolicy__NameAssignment_1");
			builder.put(grammarAccess.getSortingPolicyAccess().getCriterionAssignment_3(), "rule__SortingPolicy__CriterionAssignment_3");
			builder.put(grammarAccess.getSortingPolicyAccess().getDirectionAssignment_5(), "rule__SortingPolicy__DirectionAssignment_5");
			builder.put(grammarAccess.getSortingPolicyAccess().getAppliesToResourceAssignment_6_1(), "rule__SortingPolicy__AppliesToResourceAssignment_6_1");
			builder.put(grammarAccess.getSortingPolicyAccess().getAppliesToFeedbackAssignment_7_1(), "rule__SortingPolicy__AppliesToFeedbackAssignment_7_1");
			builder.put(grammarAccess.getSortingPolicyAccess().getInContextAssignment_8_1(), "rule__SortingPolicy__InContextAssignment_8_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RefDslGrammarAccess grammarAccess;

	@Override
	protected InternalRefDslParser createParser() {
		InternalRefDslParser result = new InternalRefDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RefDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RefDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
