/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.enorm.refdsl.ide.contentassist.antlr.internal.InternalRefDslParser;
import pt.isep.enorm.refdsl.services.RefDslGrammarAccess;

public class RefDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RefDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RefDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getPrimitiveTypeAccess().getAlternatives(), "rule__PrimitiveType__Alternatives");
			builder.put(grammarAccess.getValidationKindAccess().getAlternatives(), "rule__ValidationKind__Alternatives");
			builder.put(grammarAccess.getActionKindAccess().getAlternatives(), "rule__ActionKind__Alternatives");
			builder.put(grammarAccess.getRefModelAccess().getGroup(), "rule__RefModel__Group__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_3(), "rule__RefModel__Group_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_3_3(), "rule__RefModel__Group_3_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_4(), "rule__RefModel__Group_4__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_4_3(), "rule__RefModel__Group_4_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_5(), "rule__RefModel__Group_5__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_5_3(), "rule__RefModel__Group_5_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_6(), "rule__RefModel__Group_6__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_6_3(), "rule__RefModel__Group_6_3__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_7(), "rule__RefModel__Group_7__0");
			builder.put(grammarAccess.getRefModelAccess().getGroup_7_3(), "rule__RefModel__Group_7_3__0");
			builder.put(grammarAccess.getUserTypeAccess().getGroup(), "rule__UserType__Group__0");
			builder.put(grammarAccess.getUserTypeAccess().getGroup_2(), "rule__UserType__Group_2__0");
			builder.put(grammarAccess.getUserTypeAccess().getGroup_2_3(), "rule__UserType__Group_2_3__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup(), "rule__ResourceType__Group__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_3(), "rule__ResourceType__Group_3__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_3_3(), "rule__ResourceType__Group_3_3__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_4(), "rule__ResourceType__Group_4__0");
			builder.put(grammarAccess.getResourceTypeAccess().getGroup_4_3(), "rule__ResourceType__Group_4_3__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup(), "rule__FeedbackType__Group__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_2(), "rule__FeedbackType__Group_2__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_3(), "rule__FeedbackType__Group_3__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_4(), "rule__FeedbackType__Group_4__0");
			builder.put(grammarAccess.getFeedbackTypeAccess().getGroup_4_3(), "rule__FeedbackType__Group_4_3__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup(), "rule__FeedbackDefinition__Group__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_6(), "rule__FeedbackDefinition__Group_6__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_6_3(), "rule__FeedbackDefinition__Group_6_3__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_7(), "rule__FeedbackDefinition__Group_7__0");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getGroup_7_3(), "rule__FeedbackDefinition__Group_7_3__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup(), "rule__ValidationRule__Group__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_1(), "rule__ValidationRule__Group_1__0");
			builder.put(grammarAccess.getValidationRuleAccess().getGroup_4(), "rule__ValidationRule__Group_4__0");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getGroup(), "rule__AuthorizationRule__Group__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup(), "rule__AutomationRule__Group__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_2(), "rule__AutomationRule__Group_2__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_3(), "rule__AutomationRule__Group_3__0");
			builder.put(grammarAccess.getAutomationRuleAccess().getGroup_4(), "rule__AutomationRule__Group_4__0");
			builder.put(grammarAccess.getRefModelAccess().getNameAssignment_1(), "rule__RefModel__NameAssignment_1");
			builder.put(grammarAccess.getRefModelAccess().getUserTypesAssignment_3_2(), "rule__RefModel__UserTypesAssignment_3_2");
			builder.put(grammarAccess.getRefModelAccess().getUserTypesAssignment_3_3_1(), "rule__RefModel__UserTypesAssignment_3_3_1");
			builder.put(grammarAccess.getRefModelAccess().getResourceTypesAssignment_4_2(), "rule__RefModel__ResourceTypesAssignment_4_2");
			builder.put(grammarAccess.getRefModelAccess().getResourceTypesAssignment_4_3_1(), "rule__RefModel__ResourceTypesAssignment_4_3_1");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackTypesAssignment_5_2(), "rule__RefModel__FeedbackTypesAssignment_5_2");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackTypesAssignment_5_3_1(), "rule__RefModel__FeedbackTypesAssignment_5_3_1");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackDefinitionsAssignment_6_2(), "rule__RefModel__FeedbackDefinitionsAssignment_6_2");
			builder.put(grammarAccess.getRefModelAccess().getFeedbackDefinitionsAssignment_6_3_1(), "rule__RefModel__FeedbackDefinitionsAssignment_6_3_1");
			builder.put(grammarAccess.getRefModelAccess().getAutomationRulesAssignment_7_2(), "rule__RefModel__AutomationRulesAssignment_7_2");
			builder.put(grammarAccess.getRefModelAccess().getAutomationRulesAssignment_7_3_1(), "rule__RefModel__AutomationRulesAssignment_7_3_1");
			builder.put(grammarAccess.getUserTypeAccess().getNameAssignment_1(), "rule__UserType__NameAssignment_1");
			builder.put(grammarAccess.getUserTypeAccess().getSuperTypesAssignment_2_2(), "rule__UserType__SuperTypesAssignment_2_2");
			builder.put(grammarAccess.getUserTypeAccess().getSuperTypesAssignment_2_3_1(), "rule__UserType__SuperTypesAssignment_2_3_1");
			builder.put(grammarAccess.getResourceTypeAccess().getNameAssignment_1(), "rule__ResourceType__NameAssignment_1");
			builder.put(grammarAccess.getResourceTypeAccess().getAttributesAssignment_3_2(), "rule__ResourceType__AttributesAssignment_3_2");
			builder.put(grammarAccess.getResourceTypeAccess().getAttributesAssignment_3_3_1(), "rule__ResourceType__AttributesAssignment_3_3_1");
			builder.put(grammarAccess.getResourceTypeAccess().getAuthorizationRulesAssignment_4_2(), "rule__ResourceType__AuthorizationRulesAssignment_4_2");
			builder.put(grammarAccess.getResourceTypeAccess().getAuthorizationRulesAssignment_4_3_1(), "rule__ResourceType__AuthorizationRulesAssignment_4_3_1");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
			builder.put(grammarAccess.getAttributeAccess().getTypeAssignment_3(), "rule__Attribute__TypeAssignment_3");
			builder.put(grammarAccess.getFeedbackTypeAccess().getNameAssignment_1(), "rule__FeedbackType__NameAssignment_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getHasRatingAssignment_2_1(), "rule__FeedbackType__HasRatingAssignment_2_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getRecursiveAssignment_3_1(), "rule__FeedbackType__RecursiveAssignment_3_1");
			builder.put(grammarAccess.getFeedbackTypeAccess().getAttributesAssignment_4_2(), "rule__FeedbackType__AttributesAssignment_4_2");
			builder.put(grammarAccess.getFeedbackTypeAccess().getAttributesAssignment_4_3_1(), "rule__FeedbackType__AttributesAssignment_4_3_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getNameAssignment_1(), "rule__FeedbackDefinition__NameAssignment_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getTypeAssignment_3(), "rule__FeedbackDefinition__TypeAssignment_3");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getSubjectAssignment_5(), "rule__FeedbackDefinition__SubjectAssignment_5");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getWritersAssignment_6_2(), "rule__FeedbackDefinition__WritersAssignment_6_2");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getWritersAssignment_6_3_1(), "rule__FeedbackDefinition__WritersAssignment_6_3_1");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getValidationRulesAssignment_7_2(), "rule__FeedbackDefinition__ValidationRulesAssignment_7_2");
			builder.put(grammarAccess.getFeedbackDefinitionAccess().getValidationRulesAssignment_7_3_1(), "rule__FeedbackDefinition__ValidationRulesAssignment_7_3_1");
			builder.put(grammarAccess.getValidationRuleAccess().getNameAssignment_1_1(), "rule__ValidationRule__NameAssignment_1_1");
			builder.put(grammarAccess.getValidationRuleAccess().getKindAssignment_3(), "rule__ValidationRule__KindAssignment_3");
			builder.put(grammarAccess.getValidationRuleAccess().getImplementationIdAssignment_4_1(), "rule__ValidationRule__ImplementationIdAssignment_4_1");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getAllowedActionAssignment_2(), "rule__AuthorizationRule__AllowedActionAssignment_2");
			builder.put(grammarAccess.getAuthorizationRuleAccess().getRoleAssignment_4(), "rule__AuthorizationRule__RoleAssignment_4");
			builder.put(grammarAccess.getAutomationRuleAccess().getNameAssignment_1(), "rule__AutomationRule__NameAssignment_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getTriggerAssignment_2_1(), "rule__AutomationRule__TriggerAssignment_2_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getConditionAssignment_3_1(), "rule__AutomationRule__ConditionAssignment_3_1");
			builder.put(grammarAccess.getAutomationRuleAccess().getActionDescriptionAssignment_4_1(), "rule__AutomationRule__ActionDescriptionAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RefDslGrammarAccess grammarAccess;

	@Override
	protected InternalRefDslParser createParser() {
		InternalRefDslParser result = new InternalRefDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RefDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RefDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
