package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedAuthenticationController;
import pt.isep.enorm.ref.service.AuthenticationService;

@RestController
@RequestMapping(value = "/api/auth")
public class AuthenticationController extends GeneratedAuthenticationController {
  public AuthenticationController(AuthenticationService authenticationService) {
    super(authenticationService);
  }
}
