package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedReportOnPostController;
import pt.isep.enorm.ref.service.ReportOnPostService;

@RestController
@RequestMapping(value = "/api")
public class ReportOnPostController extends GeneratedReportOnPostController {
  public ReportOnPostController(ReportOnPostService templateService) {
    super(templateService);
  }
}
