package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedSubredditController;
import pt.isep.enorm.ref.service.SubredditService;

@RestController
@RequestMapping(value = "/api")
public class SubredditController extends GeneratedSubredditController {
  public SubredditController(SubredditService templateService) {
    super(templateService);
  }
}
