package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedVoteOnPostController;
import pt.isep.enorm.ref.service.VoteOnPostService;

@RestController
@RequestMapping(value = "/api")
public class VoteOnPostController extends GeneratedVoteOnPostController {
  public VoteOnPostController(VoteOnPostService templateService) {
    super(templateService);
  }
}
