package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedVoteOnCommentController;
import pt.isep.enorm.ref.service.VoteOnCommentService;

@RestController
@RequestMapping(value = "/api")
public class VoteOnCommentController extends GeneratedVoteOnCommentController {
  public VoteOnCommentController(VoteOnCommentService templateService) {
    super(templateService);
  }
}
