package pt.isep.enorm.ref.repository;

/*Generated by MPS */

import org.springframework.stereotype.Repository;
import pt.isep.enorm.ref.repository.generated.GeneratedAuthorizationRuleRepository;

@Repository
public interface AuthorizationRuleRepository extends GeneratedAuthorizationRuleRepository {
}
