package pt.isep.enorm.refdsl.generator;

import java.util.LinkedHashSet;
import java.util.Objects;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import pt.isep.enorm.refdsl.refDsl.Attribute;
import pt.isep.enorm.refdsl.refDsl.FeedbackDefinition;
import pt.isep.enorm.refdsl.refDsl.RatingPolicy;
import pt.isep.enorm.refdsl.refDsl.RefModel;
import pt.isep.enorm.refdsl.refDsl.ResourceType;
import pt.isep.enorm.refdsl.refDsl.UserType;

/**
 * Generates a Spring Boot backend skeleton from a REF model (P2 Activity 5 / 6).
 * Output: generated-backend/&lt;scenario&gt;/ (Maven project, Generation Gap packages).
 */
@SuppressWarnings("all")
public class RefBackendGenerator {
  private final RefBackendNaming naming = new RefBackendNaming();

  public void generate(final RefModel model, final IFileSystemAccess2 fsa) {
    final String slug = this.naming.scenarioSlug(model);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("generated-backend/");
    _builder.append(slug);
    final String root = _builder.toString();
    final String pkg = this.naming.basePackage(model);
    final String app = this.naming.scenarioPascal(model);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append(root);
    _builder_1.append("/pom.xml");
    this.write(fsa, _builder_1.toString(), this.pom(model));
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append(root);
    _builder_2.append("/README.md");
    this.write(fsa, _builder_2.toString(), this.readme(model, root));
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append(root);
    _builder_3.append("/GENERATION_MANIFEST.txt");
    this.write(fsa, _builder_3.toString(), this.manifest(model));
    StringConcatenation _builder_4 = new StringConcatenation();
    _builder_4.append(root);
    _builder_4.append("/src/main/resources/application.properties");
    this.write(fsa, _builder_4.toString(), this.applicationProperties(model));
    StringConcatenation _builder_5 = new StringConcatenation();
    _builder_5.append(root);
    _builder_5.append("/src/main/java/");
    String _replace = pkg.replace(".", "/");
    _builder_5.append(_replace);
    _builder_5.append("/");
    _builder_5.append(app);
    _builder_5.append("BackendApplication.java");
    this.write(fsa, _builder_5.toString(), this.applicationClass(model));
    StringConcatenation _builder_6 = new StringConcatenation();
    _builder_6.append(root);
    _builder_6.append("/src/main/java/");
    String _replace_1 = pkg.replace(".", "/");
    _builder_6.append(_replace_1);
    _builder_6.append("/domain/enums/Role.java");
    this.write(fsa, _builder_6.toString(), this.roleEnum(model));
    StringConcatenation _builder_7 = new StringConcatenation();
    _builder_7.append(root);
    _builder_7.append("/src/main/java/");
    String _replace_2 = pkg.replace(".", "/");
    _builder_7.append(_replace_2);
    _builder_7.append("/domain/generated/Generated");
    _builder_7.append(app);
    _builder_7.append("User.java");
    this.write(fsa, _builder_7.toString(), this.generatedUser(model));
    StringConcatenation _builder_8 = new StringConcatenation();
    _builder_8.append(root);
    _builder_8.append("/src/main/java/");
    String _replace_3 = pkg.replace(".", "/");
    _builder_8.append(_replace_3);
    _builder_8.append("/domain/");
    _builder_8.append(app);
    _builder_8.append("User.java");
    this.writeManualOnce(fsa, _builder_8.toString(), this.userSubclass(model));
    StringConcatenation _builder_9 = new StringConcatenation();
    _builder_9.append(root);
    _builder_9.append("/src/main/java/");
    String _replace_4 = pkg.replace(".", "/");
    _builder_9.append(_replace_4);
    _builder_9.append("/repository/generated/Generated");
    _builder_9.append(app);
    _builder_9.append("UserRepository.java");
    this.write(fsa, _builder_9.toString(), this.generatedUserRepository(model));
    StringConcatenation _builder_10 = new StringConcatenation();
    _builder_10.append(root);
    _builder_10.append("/src/main/java/");
    String _replace_5 = pkg.replace(".", "/");
    _builder_10.append(_replace_5);
    _builder_10.append("/repository/");
    _builder_10.append(app);
    _builder_10.append("UserRepository.java");
    this.writeManualOnce(fsa, _builder_10.toString(), this.userRepositorySubclass(model));
    EList<ResourceType> _resourceTypes = model.getResourceTypes();
    for (final ResourceType rt : _resourceTypes) {
      this.generateResource(model, fsa, root, pkg, rt);
    }
    EList<FeedbackDefinition> _feedbackDefinitions = model.getFeedbackDefinitions();
    for (final FeedbackDefinition fd : _feedbackDefinitions) {
      this.generateFeedback(model, fsa, root, pkg, fd);
    }
    StringConcatenation _builder_11 = new StringConcatenation();
    _builder_11.append(root);
    _builder_11.append("/src/main/java/");
    String _replace_6 = pkg.replace(".", "/");
    _builder_11.append(_replace_6);
    _builder_11.append("/security/SecurityConfiguration.java");
    this.write(fsa, _builder_11.toString(), this.securityConfig(model));
    StringConcatenation _builder_12 = new StringConcatenation();
    _builder_12.append(root);
    _builder_12.append("/src/main/java/");
    String _replace_7 = pkg.replace(".", "/");
    _builder_12.append(_replace_7);
    _builder_12.append("/service/generated/GeneratedAuthenticationService.java");
    this.write(fsa, _builder_12.toString(), this.generatedAuthService(model));
    StringConcatenation _builder_13 = new StringConcatenation();
    _builder_13.append(root);
    _builder_13.append("/src/main/java/");
    String _replace_8 = pkg.replace(".", "/");
    _builder_13.append(_replace_8);
    _builder_13.append("/service/AuthenticationService.java");
    this.write(fsa, _builder_13.toString(), this.authServiceSubclass(model));
    StringConcatenation _builder_14 = new StringConcatenation();
    _builder_14.append(root);
    _builder_14.append("/src/main/java/");
    String _replace_9 = pkg.replace(".", "/");
    _builder_14.append(_replace_9);
    _builder_14.append("/web/generated/GeneratedAuthenticationController.java");
    this.write(fsa, _builder_14.toString(), this.generatedAuthController(model));
    StringConcatenation _builder_15 = new StringConcatenation();
    _builder_15.append(root);
    _builder_15.append("/src/main/java/");
    String _replace_10 = pkg.replace(".", "/");
    _builder_15.append(_replace_10);
    _builder_15.append("/web/AuthenticationController.java");
    this.write(fsa, _builder_15.toString(), this.authControllerSubclass(model));
    StringConcatenation _builder_16 = new StringConcatenation();
    _builder_16.append(root);
    _builder_16.append("/src/main/java/");
    String _replace_11 = pkg.replace(".", "/");
    _builder_16.append(_replace_11);
    _builder_16.append("/web/error/ApiError.java");
    this.write(fsa, _builder_16.toString(), this.apiError(model));
    StringConcatenation _builder_17 = new StringConcatenation();
    _builder_17.append(root);
    _builder_17.append("/src/main/java/");
    String _replace_12 = pkg.replace(".", "/");
    _builder_17.append(_replace_12);
    _builder_17.append("/web/error/ApiExceptionHandler.java");
    this.write(fsa, _builder_17.toString(), this.apiExceptionHandler(model));
    StringConcatenation _builder_18 = new StringConcatenation();
    _builder_18.append(root);
    _builder_18.append("/src/test/java/");
    String _replace_13 = pkg.replace(".", "/");
    _builder_18.append(_replace_13);
    _builder_18.append("/");
    _builder_18.append(app);
    _builder_18.append("BackendApplicationTests.java");
    this.write(fsa, _builder_18.toString(), this.applicationTest(model));
  }

  public void generateResource(final RefModel model, final IFileSystemAccess2 fsa, final String root, final String pkg, final ResourceType rt) {
    final String entity = this.naming.toPascalCase(rt.getName());
    final String path = pkg.replace(".", "/");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(root);
    _builder.append("/src/main/java/");
    _builder.append(path);
    _builder.append("/domain/generated/Generated");
    _builder.append(entity);
    _builder.append(".java");
    this.write(fsa, _builder.toString(), this.generatedResourceEntity(model, rt, entity));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append(root);
    _builder_1.append("/src/main/java/");
    _builder_1.append(path);
    _builder_1.append("/domain/");
    _builder_1.append(entity);
    _builder_1.append(".java");
    this.writeManualOnce(fsa, _builder_1.toString(), this.entitySubclass(model, entity));
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append(root);
    _builder_2.append("/src/main/java/");
    _builder_2.append(path);
    _builder_2.append("/repository/generated/Generated");
    _builder_2.append(entity);
    _builder_2.append("Repository.java");
    this.write(fsa, _builder_2.toString(), this.generatedRepository(model, entity));
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append(root);
    _builder_3.append("/src/main/java/");
    _builder_3.append(path);
    _builder_3.append("/repository/");
    _builder_3.append(entity);
    _builder_3.append("Repository.java");
    this.writeManualOnce(fsa, _builder_3.toString(), this.repositorySubclass(model, entity));
    StringConcatenation _builder_4 = new StringConcatenation();
    _builder_4.append(root);
    _builder_4.append("/src/main/java/");
    _builder_4.append(path);
    _builder_4.append("/service/generated/Generated");
    _builder_4.append(entity);
    _builder_4.append("Service.java");
    this.write(fsa, _builder_4.toString(), this.generatedResourceService(model, entity));
    StringConcatenation _builder_5 = new StringConcatenation();
    _builder_5.append(root);
    _builder_5.append("/src/main/java/");
    _builder_5.append(path);
    _builder_5.append("/service/");
    _builder_5.append(entity);
    _builder_5.append("Service.java");
    this.writeManualOnce(fsa, _builder_5.toString(), this.serviceSubclass(model, entity));
    StringConcatenation _builder_6 = new StringConcatenation();
    _builder_6.append(root);
    _builder_6.append("/src/main/java/");
    _builder_6.append(path);
    _builder_6.append("/web/generated/Generated");
    _builder_6.append(entity);
    _builder_6.append("Controller.java");
    this.write(fsa, _builder_6.toString(), this.generatedResourceController(model, entity));
    StringConcatenation _builder_7 = new StringConcatenation();
    _builder_7.append(root);
    _builder_7.append("/src/main/java/");
    _builder_7.append(path);
    _builder_7.append("/web/");
    _builder_7.append(entity);
    _builder_7.append("Controller.java");
    this.writeManualOnce(fsa, _builder_7.toString(), this.resourceControllerSubclass(model, entity));
  }

  public void generateFeedback(final RefModel model, final IFileSystemAccess2 fsa, final String root, final String pkg, final FeedbackDefinition fd) {
    final String entity = this.naming.toPascalCase(fd.getName());
    final String path = pkg.replace(".", "/");
    String _xifexpression = null;
    ResourceType _subjectResource = fd.getSubjectResource();
    boolean _tripleNotEquals = (_subjectResource != null);
    if (_tripleNotEquals) {
      _xifexpression = this.naming.toPascalCase(fd.getSubjectResource().getName());
    } else {
      _xifexpression = null;
    }
    final String subject = _xifexpression;
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(root);
    _builder.append("/src/main/java/");
    _builder.append(path);
    _builder.append("/domain/generated/Generated");
    _builder.append(entity);
    _builder.append(".java");
    this.write(fsa, _builder.toString(), this.generatedFeedbackEntity(model, fd, entity, subject));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append(root);
    _builder_1.append("/src/main/java/");
    _builder_1.append(path);
    _builder_1.append("/domain/");
    _builder_1.append(entity);
    _builder_1.append(".java");
    this.writeManualOnce(fsa, _builder_1.toString(), this.entitySubclass(model, entity));
    StringConcatenation _builder_2 = new StringConcatenation();
    _builder_2.append(root);
    _builder_2.append("/src/main/java/");
    _builder_2.append(path);
    _builder_2.append("/repository/generated/Generated");
    _builder_2.append(entity);
    _builder_2.append("Repository.java");
    this.write(fsa, _builder_2.toString(), this.generatedRepository(model, entity));
    StringConcatenation _builder_3 = new StringConcatenation();
    _builder_3.append(root);
    _builder_3.append("/src/main/java/");
    _builder_3.append(path);
    _builder_3.append("/repository/");
    _builder_3.append(entity);
    _builder_3.append("Repository.java");
    this.writeManualOnce(fsa, _builder_3.toString(), this.repositorySubclass(model, entity));
    StringConcatenation _builder_4 = new StringConcatenation();
    _builder_4.append(root);
    _builder_4.append("/src/main/java/");
    _builder_4.append(path);
    _builder_4.append("/service/generated/Generated");
    _builder_4.append(entity);
    _builder_4.append("Service.java");
    this.write(fsa, _builder_4.toString(), this.generatedFeedbackService(model, fd, entity, subject));
    StringConcatenation _builder_5 = new StringConcatenation();
    _builder_5.append(root);
    _builder_5.append("/src/main/java/");
    _builder_5.append(path);
    _builder_5.append("/service/");
    _builder_5.append(entity);
    _builder_5.append("Service.java");
    this.writeManualOnce(fsa, _builder_5.toString(), this.serviceSubclass(model, entity));
    StringConcatenation _builder_6 = new StringConcatenation();
    _builder_6.append(root);
    _builder_6.append("/src/main/java/");
    _builder_6.append(path);
    _builder_6.append("/web/generated/Generated");
    _builder_6.append(entity);
    _builder_6.append("Controller.java");
    this.write(fsa, _builder_6.toString(), this.generatedFeedbackController(model, entity));
    StringConcatenation _builder_7 = new StringConcatenation();
    _builder_7.append(root);
    _builder_7.append("/src/main/java/");
    _builder_7.append(path);
    _builder_7.append("/web/");
    _builder_7.append(entity);
    _builder_7.append("Controller.java");
    this.writeManualOnce(fsa, _builder_7.toString(), this.feedbackControllerSubclass(model, entity));
  }

  public void write(final IFileSystemAccess2 fsa, final String path, final String content) {
    fsa.generateFile(path, content);
  }

  public void writeManualOnce(final IFileSystemAccess2 fsa, final String path, final String content) {
    try {
      boolean _isFile = fsa.isFile(path);
      if (_isFile) {
        return;
      }
    } catch (final Throwable _t) {
      if (_t instanceof UnsupportedOperationException) {
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
    fsa.generateFile(path, content);
  }

  public String pom(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\"");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<modelVersion>4.0.0</modelVersion>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<parent>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<artifactId>spring-boot-starter-parent</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<version>3.4.5</version>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<relativePath/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</parent>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<groupId>pt.isep.enorm.ref</groupId>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<artifactId>");
    String _artifactId = this.naming.artifactId(model);
    _builder.append(_artifactId, "    ");
    _builder.append("</artifactId>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("<version>0.0.1-SNAPSHOT</version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<description>Generated REF backend for ");
    String _name = model.getName();
    _builder.append(_name, "    ");
    _builder.append("</description>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("<properties>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<java.version>21</java.version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</properties>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<dependencies>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-web</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-data-jpa</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-validation</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-security</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>com.h2database</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>h2</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<artifactId>spring-boot-starter-test</artifactId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<scope>test</scope>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</dependencies>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<build>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<plugins>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<groupId>org.springframework.boot</groupId>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<artifactId>spring-boot-maven-plugin</artifactId>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</plugins>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</build>");
    _builder.newLine();
    _builder.append("</project>");
    _builder.newLine();
    return _builder.toString();
  }

  public String applicationProperties(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("spring.application.name=");
    String _artifactId = this.naming.artifactId(model);
    _builder.append(_artifactId);
    _builder.newLineIfNotEmpty();
    _builder.append("server.port=");
    int _serverPort = this.naming.serverPort(model);
    _builder.append(_serverPort);
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.url=jdbc:h2:file:./data/");
    String _scenarioSlug = this.naming.scenarioSlug(model);
    _builder.append(_scenarioSlug);
    _builder.append("appdb");
    _builder.newLineIfNotEmpty();
    _builder.append("spring.datasource.driver-class-name=org.h2.Driver");
    _builder.newLine();
    _builder.append("spring.datasource.username=sa");
    _builder.newLine();
    _builder.append("spring.datasource.password=");
    _builder.newLine();
    _builder.append("spring.h2.console.enabled=true");
    _builder.newLine();
    _builder.append("spring.h2.console.path=/h2-console");
    _builder.newLine();
    _builder.append("spring.jpa.hibernate.ddl-auto=update");
    _builder.newLine();
    _builder.append("spring.jpa.open-in-view=false");
    _builder.newLine();
    return _builder.toString();
  }

  public String applicationClass(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.boot.SpringApplication;");
    _builder.newLine();
    _builder.append("import org.springframework.boot.autoconfigure.SpringBootApplication;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SpringBootApplication");
    _builder.newLine();
    _builder.append("public class ");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("BackendApplication {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("SpringApplication.run(");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1, "        ");
    _builder.append("BackendApplication.class, args);");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String roleEnum(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".domain.enums;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public enum Role {");
    _builder.newLine();
    String _roleEnumLiterals = this.roleEnumLiterals(model);
    _builder.append(_roleEnumLiterals);
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String roleEnumLiterals(final RefModel model) {
    String _xblockexpression = null;
    {
      final LinkedHashSet<String> kinds = new LinkedHashSet<String>();
      EList<UserType> _userTypes = model.getUserTypes();
      for (final UserType ut : _userTypes) {
        kinds.add(ut.getKind().getLiteral());
      }
      boolean _isEmpty = kinds.isEmpty();
      if (_isEmpty) {
        kinds.add("GENERIC");
      }
      final StringBuilder sb = new StringBuilder();
      for (final String k : kinds) {
        {
          int _length = sb.length();
          boolean _greaterThan = (_length > 0);
          if (_greaterThan) {
            sb.append(",\n");
          }
          sb.append("    ").append(k);
        }
      }
      _xblockexpression = sb.toString();
    }
    return _xblockexpression;
  }

  public boolean hasRequiredAttributes(final ResourceType rt) {
    boolean _xblockexpression = false;
    {
      EList<Attribute> _attributes = rt.getAttributes();
      for (final Attribute a : _attributes) {
        boolean _isRequired = a.isRequired();
        if (_isRequired) {
          return true;
        }
      }
      _xblockexpression = false;
    }
    return _xblockexpression;
  }

  public String columnAnnotation(final Attribute a) {
    String _xblockexpression = null;
    {
      final String extra = this.naming.columnDefinition(a);
      String _xifexpression = null;
      if (((extra == null) || extra.isEmpty())) {
        boolean _isRequired = a.isRequired();
        boolean _not = (!_isRequired);
        String _plus = ("@Column(nullable = " + Boolean.valueOf(_not));
        _xifexpression = (_plus + ")");
      } else {
        boolean _isRequired_1 = a.isRequired();
        boolean _not_1 = (!_isRequired_1);
        String _plus_1 = ("@Column(nullable = " + Boolean.valueOf(_not_1));
        String _plus_2 = (_plus_1 + ", ");
        String _plus_3 = (_plus_2 + extra);
        _xifexpression = (_plus_3 + ")");
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }

  public int ratingMin(final FeedbackDefinition fd) {
    int _xifexpression = (int) 0;
    RatingPolicy _rating = fd.getRating();
    boolean _tripleEquals = (_rating == null);
    if (_tripleEquals) {
      _xifexpression = 1;
    } else {
      double _minValue = fd.getRating().getMinValue();
      _xifexpression = ((int) _minValue);
    }
    return _xifexpression;
  }

  public int ratingMax(final FeedbackDefinition fd) {
    int _xifexpression = (int) 0;
    RatingPolicy _rating = fd.getRating();
    boolean _tripleEquals = (_rating == null);
    if (_tripleEquals) {
      _xifexpression = 5;
    } else {
      double _maxValue = fd.getRating().getMaxValue();
      _xifexpression = ((int) _maxValue);
    }
    return _xifexpression;
  }

  public String generatedUserRepository(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".repository.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.data.jpa.repository.JpaRepository;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("User;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public interface Generated");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1);
    _builder.append("UserRepository extends JpaRepository<");
    String _scenarioPascal_2 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_2);
    _builder.append("User, Long> {");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String userRepositorySubclass(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".repository.generated.Generated");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("UserRepository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public interface ");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1);
    _builder.append("UserRepository extends Generated");
    String _scenarioPascal_2 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_2);
    _builder.append("UserRepository {");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedUser(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".domain.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import jakarta.persistence.Column;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.EnumType;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Enumerated;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.GeneratedValue;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.GenerationType;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Id;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.MappedSuperclass;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.enums.Role;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@MappedSuperclass");
    _builder.newLine();
    _builder.append("public abstract class Generated");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("User {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("@Id");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GeneratedValue(strategy = GenerationType.IDENTITY)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Long id;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Column(nullable = false, unique = true, length = 80)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String username;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Column(nullable = false, length = 200)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String password;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Enumerated(EnumType.STRING)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Column(nullable = false, length = 32)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Role role;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Long getId() { return id; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setId(Long id) { this.id = id; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getUsername() { return username; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setUsername(String username) { this.username = username; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getPassword() { return password; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setPassword(String password) { this.password = password; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Role getRole() { return role; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setRole(Role role) { this.role = role; }");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String userSubclass(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".domain;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import jakarta.persistence.Entity;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Table;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.generated.Generated");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("User;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("/** Manual extension point — edit scenario-specific user logic here. */");
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("@Table(name = \"users\")");
    _builder.newLine();
    _builder.append("public class ");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1);
    _builder.append("User extends Generated");
    String _scenarioPascal_2 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_2);
    _builder.append("User {");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedResourceEntity(final RefModel model, final ResourceType rt, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".domain.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import jakarta.persistence.Column;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.GeneratedValue;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.GenerationType;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Id;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.MappedSuperclass;");
    _builder.newLine();
    {
      boolean _hasRequiredAttributes = this.hasRequiredAttributes(rt);
      if (_hasRequiredAttributes) {
        _builder.append("import jakarta.validation.constraints.NotNull;");
        _builder.newLine();
      }
    }
    _builder.newLine();
    _builder.append("@MappedSuperclass");
    _builder.newLine();
    _builder.append("public abstract class Generated");
    _builder.append(entity);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("@Id");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GeneratedValue(strategy = GenerationType.IDENTITY)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Long id;");
    _builder.newLine();
    _builder.newLine();
    {
      EList<Attribute> _attributes = rt.getAttributes();
      for(final Attribute a : _attributes) {
        {
          boolean _isRequired = a.isRequired();
          if (_isRequired) {
            _builder.append("@NotNull");
            _builder.newLineIfNotEmpty();
          }
        }
        String _columnAnnotation = this.columnAnnotation(a);
        _builder.append(_columnAnnotation);
        _builder.newLineIfNotEmpty();
        _builder.append("private ");
        String _javaType = this.naming.javaType(a);
        _builder.append(_javaType);
        _builder.append(" ");
        String _name = a.getName();
        _builder.append(_name);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
      }
    }
    _builder.append("    ");
    _builder.append("public Long getId() { return id; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setId(Long id) { this.id = id; }");
    _builder.newLine();
    {
      EList<Attribute> _attributes_1 = rt.getAttributes();
      for(final Attribute a_1 : _attributes_1) {
        _builder.append("public ");
        String _javaType_1 = this.naming.javaType(a_1);
        _builder.append(_javaType_1);
        _builder.append(" get");
        String _pascalCase = this.naming.toPascalCase(a_1.getName());
        _builder.append(_pascalCase);
        _builder.append("() { return ");
        String _name_1 = a_1.getName();
        _builder.append(_name_1);
        _builder.append("; }");
        _builder.newLineIfNotEmpty();
        _builder.append("public void set");
        String _pascalCase_1 = this.naming.toPascalCase(a_1.getName());
        _builder.append(_pascalCase_1);
        _builder.append("(");
        String _javaType_2 = this.naming.javaType(a_1);
        _builder.append(_javaType_2);
        _builder.append(" ");
        String _name_2 = a_1.getName();
        _builder.append(_name_2);
        _builder.append(") { this.");
        String _name_3 = a_1.getName();
        _builder.append(_name_3);
        _builder.append(" = ");
        String _name_4 = a_1.getName();
        _builder.append(_name_4);
        _builder.append("; }");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedFeedbackEntity(final RefModel model, final FeedbackDefinition fd, final String entity, final String subject) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".domain.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import jakarta.persistence.Column;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.FetchType;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.GeneratedValue;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.GenerationType;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Id;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.JoinColumn;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.ManyToOne;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.MappedSuperclass;");
    _builder.newLine();
    _builder.append("import jakarta.validation.constraints.Max;");
    _builder.newLine();
    _builder.append("import jakarta.validation.constraints.Min;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("User;");
    _builder.newLineIfNotEmpty();
    {
      boolean _notEquals = (!Objects.equals(subject, null));
      if (_notEquals) {
        _builder.append("import ");
        String _basePackage_2 = this.naming.basePackage(model);
        _builder.append(_basePackage_2);
        _builder.append(".domain.");
        _builder.append(subject);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("@MappedSuperclass");
    _builder.newLine();
    _builder.append("public abstract class Generated");
    _builder.append(entity);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("@Id");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GeneratedValue(strategy = GenerationType.IDENTITY)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private Long id;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@ManyToOne(fetch = FetchType.LAZY, optional = false)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@JoinColumn(name = \"author_id\", nullable = false)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private ");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1, "    ");
    _builder.append("User author;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    {
      boolean _notEquals_1 = (!Objects.equals(subject, null));
      if (_notEquals_1) {
        _builder.append("@ManyToOne(fetch = FetchType.LAZY, optional = false)");
        _builder.newLine();
        _builder.append("@JoinColumn(name = \"subject_id\", nullable = false)");
        _builder.newLine();
        _builder.append("private ");
        _builder.append(subject);
        _builder.append(" subject;");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
      }
    }
    _builder.append("    ");
    _builder.append("@Column(nullable = false, length = 2000)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String comment;");
    _builder.newLine();
    _builder.newLine();
    {
      RatingPolicy _rating = fd.getRating();
      boolean _notEquals_2 = (!Objects.equals(_rating, null));
      if (_notEquals_2) {
        _builder.append("@Min(");
        int _ratingMin = this.ratingMin(fd);
        _builder.append(_ratingMin);
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("@Max(");
        int _ratingMax = this.ratingMax(fd);
        _builder.append(_ratingMax);
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("@Column(nullable = false)");
        _builder.newLine();
        _builder.append("private int grade;");
        _builder.newLine();
        _builder.newLine();
      }
    }
    _builder.append("    ");
    _builder.append("public Long getId() { return id; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setId(Long id) { this.id = id; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    String _scenarioPascal_2 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_2, "    ");
    _builder.append("User getAuthor() { return author; }");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("public void setAuthor(");
    String _scenarioPascal_3 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_3, "    ");
    _builder.append("User author) { this.author = author; }");
    _builder.newLineIfNotEmpty();
    {
      boolean _notEquals_3 = (!Objects.equals(subject, null));
      if (_notEquals_3) {
        _builder.append("public ");
        _builder.append(subject);
        _builder.append(" getSubject() { return subject; }");
        _builder.newLineIfNotEmpty();
        _builder.append("public void setSubject(");
        _builder.append(subject);
        _builder.append(" subject) { this.subject = subject; }");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("    ");
    _builder.append("public String getComment() { return comment; }");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setComment(String comment) { this.comment = comment; }");
    _builder.newLine();
    {
      RatingPolicy _rating_1 = fd.getRating();
      boolean _notEquals_4 = (!Objects.equals(_rating_1, null));
      if (_notEquals_4) {
        _builder.append("public int getGrade() { return grade; }");
        _builder.newLine();
        _builder.append("public void setGrade(int grade) { this.grade = grade; }");
        _builder.newLine();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String entitySubclass(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".domain;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import jakarta.persistence.Entity;");
    _builder.newLine();
    _builder.append("import jakarta.persistence.Table;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.generated.Generated");
    _builder.append(entity);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("/** Manual extension point — add domain invariants or helpers here. */");
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("@Table(name = \"");
    String _tableName = this.naming.tableName(entity);
    _builder.append(_tableName);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("public class ");
    _builder.append(entity);
    _builder.append(" extends Generated");
    _builder.append(entity);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedRepository(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".repository.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.data.jpa.repository.JpaRepository;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    _builder.append(entity);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public interface Generated");
    _builder.append(entity);
    _builder.append("Repository extends JpaRepository<");
    _builder.append(entity);
    _builder.append(", Long> {");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String repositorySubclass(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".repository.generated.Generated");
    _builder.append(entity);
    _builder.append("Repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("/** Manual extension point — add custom queries here. */");
    _builder.newLine();
    _builder.append("public interface ");
    _builder.append(entity);
    _builder.append("Repository extends Generated");
    _builder.append(entity);
    _builder.append("Repository {");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedResourceService(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".service.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    _builder.append(entity);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".repository.");
    _builder.append(entity);
    _builder.append("Repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Service");
    _builder.newLine();
    _builder.append("public class Generated");
    _builder.append(entity);
    _builder.append("Service {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("private final ");
    _builder.append(entity, "    ");
    _builder.append("Repository repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Generated");
    _builder.append(entity, "    ");
    _builder.append("Service(");
    _builder.append(entity, "    ");
    _builder.append("Repository repository) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("this.repository = repository;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public List<");
    _builder.append(entity, "    ");
    _builder.append("> findAll() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return repository.findAll();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append(" findById(Long id) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return repository.findById(id).orElseThrow(() -> new IllegalArgumentException(\"");
    _builder.append(entity, "        ");
    _builder.append(" not found: \" + id));");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append(" create(");
    _builder.append(entity, "    ");
    _builder.append(" entity) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return repository.save(entity);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/** Override in manual ");
    _builder.append(entity, "    ");
    _builder.append("Service for scenario-specific rules. */");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("protected void beforeCreate(");
    _builder.append(entity, "    ");
    _builder.append(" entity) {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedFeedbackService(final RefModel model, final FeedbackDefinition fd, final String entity, final String subject) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".service.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    _builder.append(entity);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".repository.");
    _builder.append(entity);
    _builder.append("Repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Service");
    _builder.newLine();
    _builder.append("public class Generated");
    _builder.append(entity);
    _builder.append("Service {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("private final ");
    _builder.append(entity, "    ");
    _builder.append("Repository repository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Generated");
    _builder.append(entity, "    ");
    _builder.append("Service(");
    _builder.append(entity, "    ");
    _builder.append("Repository repository) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("this.repository = repository;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public List<");
    _builder.append(entity, "    ");
    _builder.append("> findAll() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return repository.findAll();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append(" submit(");
    _builder.append(entity, "    ");
    _builder.append(" feedback) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("beforeSubmit(feedback);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return repository.save(feedback);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/** Override in manual service for verification, moderation, etc. */");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void beforeSubmit(");
    _builder.append(entity, "    ");
    _builder.append(" feedback) {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String serviceSubclass(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".repository.");
    _builder.append(entity);
    _builder.append("Repository;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".service.generated.Generated");
    _builder.append(entity);
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Service");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(entity);
    _builder.append("Service extends Generated");
    _builder.append(entity);
    _builder.append("Service {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append("Service(");
    _builder.append(entity, "    ");
    _builder.append("Repository repository) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("super(repository);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedResourceController(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import org.springframework.http.HttpStatus;");
    _builder.newLine();
    _builder.append("import org.springframework.http.ResponseEntity;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.GetMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.PathVariable;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.PostMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestBody;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    _builder.append(entity);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".service.");
    _builder.append(entity);
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public abstract class Generated");
    _builder.append(entity);
    _builder.append("Controller {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("private final ");
    _builder.append(entity, "    ");
    _builder.append("Service service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected Generated");
    _builder.append(entity, "    ");
    _builder.append("Controller(");
    _builder.append(entity, "    ");
    _builder.append("Service service) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("this.service = service;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GetMapping");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public List<");
    _builder.append(entity, "    ");
    _builder.append("> list() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return service.findAll();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GetMapping(\"/{id}\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append(" get(@PathVariable Long id) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return service.findById(id);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@PostMapping");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ResponseEntity<");
    _builder.append(entity, "    ");
    _builder.append("> create(@RequestBody ");
    _builder.append(entity, "    ");
    _builder.append(" body) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return ResponseEntity.status(HttpStatus.CREATED).body(service.create(body));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedFeedbackController(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import org.springframework.http.HttpStatus;");
    _builder.newLine();
    _builder.append("import org.springframework.http.ResponseEntity;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.GetMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.PostMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestBody;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    _builder.append(entity);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".service.");
    _builder.append(entity);
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public abstract class Generated");
    _builder.append(entity);
    _builder.append("Controller {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("private final ");
    _builder.append(entity, "    ");
    _builder.append("Service service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected Generated");
    _builder.append(entity, "    ");
    _builder.append("Controller(");
    _builder.append(entity, "    ");
    _builder.append("Service service) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("this.service = service;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@GetMapping");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public List<");
    _builder.append(entity, "    ");
    _builder.append("> list() {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return service.findAll();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@PostMapping");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ResponseEntity<");
    _builder.append(entity, "    ");
    _builder.append("> submit(@RequestBody ");
    _builder.append(entity, "    ");
    _builder.append(" body) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("return ResponseEntity.status(HttpStatus.CREATED).body(service.submit(body));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String resourceControllerSubclass(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RestController;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".service.");
    _builder.append(entity);
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".web.generated.Generated");
    _builder.append(entity);
    _builder.append("Controller;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@RestController");
    _builder.newLine();
    _builder.append("@RequestMapping(\"");
    String _apiCollectionPath = this.naming.apiCollectionPath(entity);
    _builder.append(_apiCollectionPath);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("public class ");
    _builder.append(entity);
    _builder.append("Controller extends Generated");
    _builder.append(entity);
    _builder.append("Controller {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append("Controller(");
    _builder.append(entity, "    ");
    _builder.append("Service service) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("super(service);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String feedbackControllerSubclass(final RefModel model, final String entity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RestController;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".service.");
    _builder.append(entity);
    _builder.append("Service;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".web.generated.Generated");
    _builder.append(entity);
    _builder.append("Controller;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@RestController");
    _builder.newLine();
    _builder.append("@RequestMapping(\"");
    String _apiCollectionPath = this.naming.apiCollectionPath(entity);
    _builder.append(_apiCollectionPath);
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("public class ");
    _builder.append(entity);
    _builder.append("Controller extends Generated");
    _builder.append(entity);
    _builder.append("Controller {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(entity, "    ");
    _builder.append("Controller(");
    _builder.append(entity, "    ");
    _builder.append("Service service) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("super(service);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedAuthService(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".service.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("User;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".domain.enums.Role;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_3 = this.naming.basePackage(model);
    _builder.append(_basePackage_3);
    _builder.append(".repository.");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1);
    _builder.append("UserRepository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Service");
    _builder.newLine();
    _builder.append("public class GeneratedAuthenticationService {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private final ");
    String _scenarioPascal_2 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_2, "    ");
    _builder.append("UserRepository userRepository;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public GeneratedAuthenticationService(");
    String _scenarioPascal_3 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_3, "    ");
    _builder.append("UserRepository userRepository) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("this.userRepository = userRepository;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    String _scenarioPascal_4 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_4, "    ");
    _builder.append("User register(String username, String password, Role role) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    String _scenarioPascal_5 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_5, "        ");
    _builder.append("User user = new ");
    String _scenarioPascal_6 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_6, "        ");
    _builder.append("User();");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("user.setUsername(username);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("user.setPassword(password);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("user.setRole(role);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return userRepository.save(user);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String authServiceSubclass(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".service;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.stereotype.Service;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".repository.");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("UserRepository;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".service.generated.GeneratedAuthenticationService;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Service");
    _builder.newLine();
    _builder.append("public class AuthenticationService extends GeneratedAuthenticationService {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public AuthenticationService(");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1, "    ");
    _builder.append("UserRepository userRepository) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("super(userRepository);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String generatedAuthController(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web.generated;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.http.HttpStatus;");
    _builder.newLine();
    _builder.append("import org.springframework.http.ResponseEntity;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.PostMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestBody;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestParam;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".domain.");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("User;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".domain.enums.Role;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_3 = this.naming.basePackage(model);
    _builder.append(_basePackage_3);
    _builder.append(".service.AuthenticationService;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public abstract class GeneratedAuthenticationController {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private final AuthenticationService authenticationService;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected GeneratedAuthenticationController(AuthenticationService authenticationService) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.authenticationService = authenticationService;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@PostMapping(\"/register\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ResponseEntity<");
    String _scenarioPascal_1 = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal_1, "    ");
    _builder.append("User> register(");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("@RequestParam String username,");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("@RequestParam String password,");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("@RequestParam(defaultValue = \"GENERIC\") Role role");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(") {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return ResponseEntity.status(HttpStatus.CREATED)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(".body(authenticationService.register(username, password, role));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String authControllerSubclass(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RequestMapping;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RestController;");
    _builder.newLine();
    _builder.append("import ");
    String _basePackage_1 = this.naming.basePackage(model);
    _builder.append(_basePackage_1);
    _builder.append(".service.AuthenticationService;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _basePackage_2 = this.naming.basePackage(model);
    _builder.append(_basePackage_2);
    _builder.append(".web.generated.GeneratedAuthenticationController;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@RestController");
    _builder.newLine();
    _builder.append("@RequestMapping(\"/api/auth\")");
    _builder.newLine();
    _builder.append("public class AuthenticationController extends GeneratedAuthenticationController {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public AuthenticationController(AuthenticationService authenticationService) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("super(authenticationService);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String securityConfig(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".security;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.context.annotation.Bean;");
    _builder.newLine();
    _builder.append("import org.springframework.context.annotation.Configuration;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.web.builders.HttpSecurity;");
    _builder.newLine();
    _builder.append("import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;");
    _builder.newLine();
    _builder.append("import org.springframework.security.web.SecurityFilterChain;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Configuration");
    _builder.newLine();
    _builder.append("@EnableWebSecurity");
    _builder.newLine();
    _builder.append("public class SecurityConfiguration {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Bean");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("http.csrf(csrf -> csrf.disable())");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(".headers(headers -> headers.frameOptions(frame -> frame.sameOrigin()))");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(".authorizeHttpRequests(auth -> auth.anyRequest().permitAll());");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return http.build();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String apiError(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web.error;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public record ApiError(String message) {");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String apiExceptionHandler(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(".web.error;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.springframework.http.HttpStatus;");
    _builder.newLine();
    _builder.append("import org.springframework.http.ResponseEntity;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.ExceptionHandler;");
    _builder.newLine();
    _builder.append("import org.springframework.web.bind.annotation.RestControllerAdvice;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@RestControllerAdvice");
    _builder.newLine();
    _builder.append("public class ApiExceptionHandler {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@ExceptionHandler(IllegalArgumentException.class)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ResponseEntity<ApiError> handleIllegalArgument(IllegalArgumentException ex) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new ApiError(ex.getMessage()));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String applicationTest(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.junit.jupiter.api.Test;");
    _builder.newLine();
    _builder.append("import org.springframework.boot.test.context.SpringBootTest;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SpringBootTest");
    _builder.newLine();
    _builder.append("class ");
    String _scenarioPascal = this.naming.scenarioPascal(model);
    _builder.append(_scenarioPascal);
    _builder.append("BackendApplicationTests {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("@Test");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("void contextLoads() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public String readme(final RefModel model, final String root) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# Generated REF Backend — ");
    String _name = model.getName();
    _builder.append(_name);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("Generated by Xtext `RefBackendGenerator` from a `.refdsl` model (P2 Activity 5/6).");
    _builder.newLine();
    _builder.newLine();
    _builder.append("## Run");
    _builder.newLine();
    _builder.newLine();
    _builder.append("```powershell");
    _builder.newLine();
    _builder.append("mvn -f ");
    _builder.append(root);
    _builder.append("/pom.xml spring-boot:run");
    _builder.newLineIfNotEmpty();
    _builder.append("```");
    _builder.newLine();
    _builder.newLine();
    _builder.append("Port: ");
    int _serverPort = this.naming.serverPort(model);
    _builder.append(_serverPort);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("## Structure (Generation Gap)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("- `domain/generated`, `repository/generated`, `service/generated`, `web/generated` — regenerated on each DSL save");
    _builder.newLine();
    _builder.append("- Classes without `generated` in the package — manual extension points (preserved across regeneration)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("## Regenerate");
    _builder.newLine();
    _builder.newLine();
    _builder.append("Open the `.refdsl` file in the RefDsl Editor (runtime Eclipse) and save — output appears under `");
    _builder.append(root);
    _builder.append("/`.");
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }

  public String manifest(final RefModel model) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("REF backend generation manifest");
    _builder.newLine();
    _builder.append("Model: ");
    String _name = model.getName();
    _builder.append(_name);
    _builder.append(" v");
    String _xifexpression = null;
    String _version = model.getVersion();
    boolean _tripleNotEquals = (_version != null);
    if (_tripleNotEquals) {
      _xifexpression = model.getVersion();
    } else {
      _xifexpression = "n/a";
    }
    _builder.append(_xifexpression);
    _builder.newLineIfNotEmpty();
    _builder.append("Scenario slug: ");
    String _scenarioSlug = this.naming.scenarioSlug(model);
    _builder.append(_scenarioSlug);
    _builder.newLineIfNotEmpty();
    _builder.append("Package: ");
    String _basePackage = this.naming.basePackage(model);
    _builder.append(_basePackage);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("Resources: ");
    final Function1<ResourceType, String> _function = (ResourceType it) -> {
      return it.getName();
    };
    String _join = IterableExtensions.join(ListExtensions.<ResourceType, String>map(model.getResourceTypes(), _function), ", ");
    _builder.append(_join);
    _builder.newLineIfNotEmpty();
    _builder.append("Feedbacks: ");
    final Function1<FeedbackDefinition, String> _function_1 = (FeedbackDefinition it) -> {
      return it.getName();
    };
    String _join_1 = IterableExtensions.join(ListExtensions.<FeedbackDefinition, String>map(model.getFeedbackDefinitions(), _function_1), ", ");
    _builder.append(_join_1);
    _builder.newLineIfNotEmpty();
    _builder.append("User kinds: ");
    final Function1<UserType, String> _function_2 = (UserType it) -> {
      return it.getKind().getLiteral();
    };
    String _join_2 = IterableExtensions.join(ListExtensions.<UserType, String>map(model.getUserTypes(), _function_2), ", ");
    _builder.append(_join_2);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("Common (always): pom, application, security baseline, user entity, API error handler");
    _builder.newLine();
    _builder.append("Variable: one stack per ResourceType and FeedbackDefinition in the model");
    _builder.newLine();
    _builder.append("Manual: subclasses in domain/repository/service/web without \"generated\" in package name");
    _builder.newLine();
    return _builder.toString();
  }
}
