/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import pt.isep.enorm.refdsl.refDsl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage
 * @generated
 */
public class RefDslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static RefDslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RefDslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = RefDslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RefDslSwitch<Adapter> modelSwitch =
    new RefDslSwitch<Adapter>()
    {
      @Override
      public Adapter caseRefModel(RefModel object)
      {
        return createRefModelAdapter();
      }
      @Override
      public Adapter caseUserType(UserType object)
      {
        return createUserTypeAdapter();
      }
      @Override
      public Adapter caseResourceType(ResourceType object)
      {
        return createResourceTypeAdapter();
      }
      @Override
      public Adapter caseAttribute(Attribute object)
      {
        return createAttributeAdapter();
      }
      @Override
      public Adapter caseFeedbackType(FeedbackType object)
      {
        return createFeedbackTypeAdapter();
      }
      @Override
      public Adapter caseFeedbackDefinition(FeedbackDefinition object)
      {
        return createFeedbackDefinitionAdapter();
      }
      @Override
      public Adapter caseValidationRule(ValidationRule object)
      {
        return createValidationRuleAdapter();
      }
      @Override
      public Adapter caseAuthorizationRule(AuthorizationRule object)
      {
        return createAuthorizationRuleAdapter();
      }
      @Override
      public Adapter caseAutomationRule(AutomationRule object)
      {
        return createAutomationRuleAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.RefModel <em>Ref Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.RefModel
   * @generated
   */
  public Adapter createRefModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.UserType <em>User Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.UserType
   * @generated
   */
  public Adapter createUserTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.ResourceType <em>Resource Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.ResourceType
   * @generated
   */
  public Adapter createResourceTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.Attribute
   * @generated
   */
  public Adapter createAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.FeedbackType <em>Feedback Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.FeedbackType
   * @generated
   */
  public Adapter createFeedbackTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.FeedbackDefinition <em>Feedback Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.FeedbackDefinition
   * @generated
   */
  public Adapter createFeedbackDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.ValidationRule <em>Validation Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.ValidationRule
   * @generated
   */
  public Adapter createValidationRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.AuthorizationRule <em>Authorization Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.AuthorizationRule
   * @generated
   */
  public Adapter createAuthorizationRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule <em>Automation Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see pt.isep.enorm.refdsl.refDsl.AutomationRule
   * @generated
   */
  public Adapter createAutomationRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //RefDslAdapterFactory
