package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedChannelService;
import pt.isep.enorm.ref.repository.ChannelRepository;
import pt.isep.enorm.ref.domain.Channel;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;

@Service
public class ChannelService extends GeneratedChannelService {

  private final ModerationService moderationService;

  public ChannelService(ChannelRepository feedbackRepository, ModerationService moderationServices) {
    super(feedbackRepository);
    this.moderationService = moderationServices;
  }

  @Override
  protected void afterChannelCreated(Channel savedResource) {
    moderationService.moderateAutomatically("Resource", savedResource.getId(), TriggerEvent.ON_RESOURCE_CREATE, moderationContent(savedResource));
  }
  protected String moderationContent(Channel savedResource) {
    return savedResource.toString();
  }

}
