package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedLikeOnCommentService;
import pt.isep.enorm.ref.repository.LikeOnCommentRepository;

@Service
public class LikeOnCommentService extends GeneratedLikeOnCommentService {


  public LikeOnCommentService(LikeOnCommentRepository feedbackRepository) {
    super(feedbackRepository);
  }


}
