package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedReportOnVideoService;
import pt.isep.enorm.ref.repository.ReportOnVideoRepository;

@Service
public class ReportOnVideoService extends GeneratedReportOnVideoService {


  public ReportOnVideoService(ReportOnVideoRepository feedbackRepository) {
    super(feedbackRepository);
  }


}
