package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedSubscriptionOnChannelService;
import pt.isep.enorm.ref.repository.SubscriptionOnChannelRepository;

@Service
public class SubscriptionOnChannelService extends GeneratedSubscriptionOnChannelService {


  public SubscriptionOnChannelService(SubscriptionOnChannelRepository feedbackRepository) {
    super(feedbackRepository);
  }


}
