package pt.isep.enorm.ref.config;

/*Generated by MPS */

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.ApplicationRunner;
import pt.isep.enorm.ref.repository.UserTypeRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import pt.isep.enorm.ref.domain.enums.UserKind;
import pt.isep.enorm.ref.repository.AuthorizationRuleRepository;
import pt.isep.enorm.ref.domain.enums.ActionKind;
import pt.isep.enorm.ref.repository.ModerationPolicyRepository;
import pt.isep.enorm.ref.domain.enums.ModerationMode;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;
import pt.isep.enorm.ref.domain.enums.ModerationDecision;
import pt.isep.enorm.ref.domain.UserType;
import pt.isep.enorm.ref.domain.ModerationPolicy;
import pt.isep.enorm.ref.domain.AuthorizationRule;

@Configuration
public class InitialDataConfiguration {
  @Bean
  /*package*/ ApplicationRunner seedDslUsers(final UserTypeRepository userTypeRepository, final PasswordEncoder passwordEncoder) {
    return (args) -> {
      seedUser(userTypeRepository, passwordEncoder, "Reviewer", UserKind.GENERIC);
      seedUser(userTypeRepository, passwordEncoder, "Buyer", UserKind.BUYER);
      seedUser(userTypeRepository, passwordEncoder, "Seller", UserKind.SELLER);
      seedUser(userTypeRepository, passwordEncoder, "Moderator", UserKind.MODERATOR);
    };
  }

  @Bean
  /*package*/ ApplicationRunner seedDslAuthorizationRules(final AuthorizationRuleRepository authorizationRuleRepository) {
    return (args) -> {
      seedAuthorizationRule(authorizationRuleRepository, "BuyerCanCreateReview", ActionKind.CREATE, UserKind.GENERIC, "Product", "ProductReview");
      seedAuthorizationRule(authorizationRuleRepository, "ReviewerCanCreateReview", ActionKind.CREATE, UserKind.GENERIC, "Product", "ProductReview");
      seedAuthorizationRule(authorizationRuleRepository, "ModeratorCanModerateReviews", ActionKind.MODERATE, UserKind.MODERATOR, "Product", "ProductReview");
      seedAuthorizationRule(authorizationRuleRepository, "BuyerCanVoteHelpful", ActionKind.VOTE, UserKind.BUYER, "CommentReview", "HelpfulVoteOnComment");
    };
  }

  @Bean
  /*package*/ ApplicationRunner seedDslModerationPolicies(final ModerationPolicyRepository moderationPolicyRepository) {
    return (args) -> seedModerationPolicy(moderationPolicyRepository, "ReviewModerationPolicy", ModerationMode.HYBRID, TriggerEvent.ON_REPORT_THRESHOLD, ModerationDecision.FLAGGED, "Product", "ProductReview", UserKind.MODERATOR);
  }


  private void seedUser(UserTypeRepository serRepository, PasswordEncoder passwordEncoder, String username, UserKind kind) {
    if (serRepository.existsByUsername(username)) {
      return;
    }
    UserType user = new UserType();
    user.setUsername(username);
    user.setPassword(passwordEncoder.encode(username));
    user.setRole(kind);
    serRepository.save(user);
  }

  private void seedModerationPolicy(ModerationPolicyRepository moderationPolicyRepository, final String name, ModerationMode mode, TriggerEvent trigger, ModerationDecision decision, String monitorsResource, String monitorsFeedback, UserKind executedByKind) {
    boolean exists = moderationPolicyRepository.findAll().stream().anyMatch((policy) -> name.equals(((ModerationPolicy) policy).getName()));
    if (exists) {
      return;
    }
    ModerationPolicy policy = new ModerationPolicy();
    policy.setName(name);
    policy.setMode(mode);
    policy.setTrigger(trigger);
    policy.setDecision(decision);
    policy.setMonitorsResource(monitorsResource);
    policy.setMonitorsFeedback(monitorsFeedback);
    policy.setExecutedByKind(executedByKind);
    moderationPolicyRepository.save(policy);
  }

  private void seedAuthorizationRule(AuthorizationRuleRepository authorizationRuleRepository, final String name, ActionKind allowedAction, UserKind actorKind, String resourceTarget, String feedbackTarget) {
    boolean exists = authorizationRuleRepository.findAll().stream().anyMatch((rule) -> name.equals(((AuthorizationRule) rule).getName()));
    if (exists) {
      return;
    }
    AuthorizationRule rule = new AuthorizationRule();
    rule.setName(name);
    rule.setAllowedAction(allowedAction);
    rule.setActorKind(actorKind);
    rule.setResourceTarget(resourceTarget);
    rule.setFeedbackTarget(feedbackTarget);
    authorizationRuleRepository.save(rule);
  }

}
