/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.ActionKind;
import pt.isep.enorm.ref.ref.ContextType;
import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.UserType;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.AuthorizationRule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AuthorizationRuleValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateAllowedAction(ActionKind value);

	boolean validateActor(UserType value);

	boolean validateContext(ContextType value);

	boolean validateResourceTarget(ResourceType value);

	boolean validateFeedbackTarget(FeedbackDefinition value);
}
