/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import org.eclipse.emf.common.util.EList;
import pt.isep.enorm.ref.ref.Action;
import pt.isep.enorm.ref.ref.Condition;
import pt.isep.enorm.ref.ref.ContextType;
import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.TriggerEvent;
import pt.isep.enorm.ref.ref.ValidationRule;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.AutomationRule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AutomationRuleValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateTrigger(TriggerEvent value);

	boolean validateTrigger(String value);

	boolean validateCondition(String value);

	boolean validateActionDescription(String value);

	boolean validateContext(ResourceType value);

	boolean validateInContext(ContextType value);

	boolean validateOnFeedback(FeedbackDefinition value);

	boolean validateUses(ValidationRule value);

	boolean validateConditions(EList<Condition> value);

	boolean validateActions(EList<Action> value);
}
