/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import org.eclipse.emf.common.util.EList;
import pt.isep.enorm.ref.ref.Attribute;
import pt.isep.enorm.ref.ref.ConditionOperator;
import pt.isep.enorm.ref.ref.ConditionValue;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.Condition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateField(String value);

	boolean validateOperator(ConditionOperator value);

	boolean validateAttribute(Attribute value);

	boolean validateChildren(EList<ConditionValue> value);

	boolean validateValue(String value);
}
