/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import org.eclipse.emf.common.util.EList;

import pt.isep.enorm.ref.ref.ContextKind;
import pt.isep.enorm.ref.ref.ResourceType;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.ContextType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContextTypeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateKind(ContextKind value);

	boolean validateContains(EList<ResourceType> value);
}
