/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.FeedbackKind;
import pt.isep.enorm.ref.ref.FeedbackPolarity;
import pt.isep.enorm.ref.ref.FeedbackSubjectScope;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.FeedbackType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeedbackTypeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateKind(FeedbackKind value);

	boolean validateSubjectScope(FeedbackSubjectScope value);

	boolean validateHasRating(boolean value);

	boolean validateRecursive(boolean value);

	boolean validateAllowsText(boolean value);

	boolean validateAllowsMedia(boolean value);

	boolean validatePolarity(FeedbackPolarity value);
}
