/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.FeedbackPolicy;
import pt.isep.enorm.ref.ref.FeedbackType;
import pt.isep.enorm.ref.ref.RatingPolicy;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.UserType;
import pt.isep.enorm.ref.ref.VerificationRequirement;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.FeedbackDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeedbackDefinitionValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateRequiresVerifiedContext(boolean value);

	boolean validateVerificationRequirement(VerificationRequirement value);

	boolean validateUniquePerAuthorTarget(boolean value);

	boolean validateType(FeedbackType value);

	boolean validateSubjectResource(ResourceType value);

	boolean validateAuthor(UserType value);

	boolean validateSubjectFeedback(FeedbackDefinition value);

	boolean validateParent(FeedbackDefinition value);

	boolean validatePolicy(FeedbackPolicy value);

	boolean validateRating(RatingPolicy value);
}
