/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.FeedbackStatus;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.FeedbackPolicy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeedbackPolicyValidator {
	boolean validate();

	boolean validateStatus(FeedbackStatus value);
}
