/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.ContextType;
import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.ModerationDecision;
import pt.isep.enorm.ref.ref.ModerationMode;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.TriggerEvent;
import pt.isep.enorm.ref.ref.UserType;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.ModerationPolicy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModerationPolicyValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateMode(ModerationMode value);

	boolean validateTrigger(TriggerEvent value);

	boolean validateTrigger(String value);

	boolean validateDecision(ModerationDecision value);

	boolean validateMonitorsResource(ResourceType value);

	boolean validateMonitorsFeedback(FeedbackDefinition value);

	boolean validateExecutedBy(UserType value);

	boolean validateInContext(ContextType value);
}
