/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.RatingScaleKind;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.RatingPolicy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RatingPolicyValidator {
	boolean validate();

	boolean validateMinValue(double value);

	boolean validateMaxValue(double value);

	boolean validateStep(double value);

	boolean validateScaleKind(RatingScaleKind value);
}
