/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import org.eclipse.emf.common.util.EList;

import pt.isep.enorm.ref.ref.AuthorizationRule;
import pt.isep.enorm.ref.ref.AutomationRule;
import pt.isep.enorm.ref.ref.ContextType;
import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.FeedbackType;
import pt.isep.enorm.ref.ref.ModerationPolicy;
import pt.isep.enorm.ref.ref.ResourceRelation;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.SortingPolicy;
import pt.isep.enorm.ref.ref.UserType;
import pt.isep.enorm.ref.ref.ValidationRule;
import pt.isep.enorm.ref.ref.VerificationPolicy;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.RefModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RefModelValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateVersion(String value);

	boolean validateUserTypes(EList<UserType> value);

	boolean validateResourceTypes(EList<ResourceType> value);

	boolean validateContextTypes(EList<ContextType> value);

	boolean validateResourceRelations(EList<ResourceRelation> value);

	boolean validateFeedbackTypes(EList<FeedbackType> value);

	boolean validateFeedbackDefinitions(EList<FeedbackDefinition> value);

	boolean validateAuthorizationRules(EList<AuthorizationRule> value);

	boolean validateValidationRules(EList<ValidationRule> value);

	boolean validateModerationPolicies(EList<ModerationPolicy> value);

	boolean validateAutomationRules(EList<AutomationRule> value);

	boolean validateVerificationPolicies(EList<VerificationPolicy> value);

	boolean validateSortingPolicies(EList<SortingPolicy> value);
}
