/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import org.eclipse.emf.common.util.EList;

import pt.isep.enorm.ref.ref.Attribute;
import pt.isep.enorm.ref.ref.ResourceType;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.ResourceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceTypeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateSupportsMedia(boolean value);

	boolean validateSuperTypes(EList<ResourceType> value);

	boolean validateAttributes(EList<Attribute> value);
}
