/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.ContextType;
import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.SortCriterion;
import pt.isep.enorm.ref.ref.SortDirection;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.SortingPolicy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SortingPolicyValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateCriterion(SortCriterion value);

	boolean validateDirection(SortDirection value);

	boolean validateAppliesToResource(ResourceType value);

	boolean validateAppliesToFeedback(FeedbackDefinition value);

	boolean validateInContext(ContextType value);
}
