/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import org.eclipse.emf.common.util.EList;

import pt.isep.enorm.ref.ref.UserKind;
import pt.isep.enorm.ref.ref.UserType;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.UserType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UserTypeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateKind(UserKind value);

	boolean validateSuperTypes(EList<UserType> value);
}
