/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.AutomationRule;
import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.ResourceType;
import pt.isep.enorm.ref.ref.RuleSeverity;
import pt.isep.enorm.ref.ref.ValidationKind;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.ValidationRule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValidationRuleValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateKind(ValidationKind value);

	boolean validateSeverity(RuleSeverity value);

	boolean validateExpression(String value);

	boolean validateImplementationId(String value);

	boolean validateAppliesToResource(ResourceType value);

	boolean validateAppliesToFeedback(FeedbackDefinition value);

	boolean validateInvokedBy(AutomationRule value);
}
