/**
 *
 * $Id$
 */
package pt.isep.enorm.ref.ref.validation;

import pt.isep.enorm.ref.ref.FeedbackDefinition;
import pt.isep.enorm.ref.ref.TriggerEvent;
import pt.isep.enorm.ref.ref.ValidationKind;

/**
 * A sample validator interface for {@link pt.isep.enorm.ref.ref.VerificationPolicy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VerificationPolicyValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateMode(ValidationKind value);

	boolean validateAppliesWhen(TriggerEvent value);

	boolean validateAppliesWhen(String value);

	boolean validateVerifies(FeedbackDefinition value);
}
