package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedLikeOnVideo;

@Entity(name = "LikeOnVideo")
@Table(name = "like_on_videos")
public class LikeOnVideo extends GeneratedLikeOnVideo {
}
