package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedLikeOnComment;

@Entity(name = "LikeOnComment")
@Table(name = "like_on_comments")
public class LikeOnComment extends GeneratedLikeOnComment {
}
