package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedReportOnComment;

@Entity(name = "ReportOnComment")
@Table(name = "report_on_comments")
public class ReportOnComment extends GeneratedReportOnComment {
}
