package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedReportOnVideoMediaReference;

@Entity(name = "ReportOnVideoMediaReference")
@Table(name = "reportonvideo_media_references")
public class ReportOnVideoMediaReference extends GeneratedReportOnVideoMediaReference {
}
