package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedSubscriptionOnChannel;

@Entity(name = "SubscriptionOnChannel")
@Table(name = "subscription_on_channels")
public class SubscriptionOnChannel extends GeneratedSubscriptionOnChannel {
}
