/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import pt.isep.enorm.refdsl.refDsl.Attribute;
import pt.isep.enorm.refdsl.refDsl.AuthorizationRule;
import pt.isep.enorm.refdsl.refDsl.AutomationRule;
import pt.isep.enorm.refdsl.refDsl.FeedbackDefinition;
import pt.isep.enorm.refdsl.refDsl.FeedbackType;
import pt.isep.enorm.refdsl.refDsl.RefDslPackage;
import pt.isep.enorm.refdsl.refDsl.RefModel;
import pt.isep.enorm.refdsl.refDsl.ResourceType;
import pt.isep.enorm.refdsl.refDsl.UserType;
import pt.isep.enorm.refdsl.refDsl.ValidationRule;
import pt.isep.enorm.refdsl.services.RefDslGrammarAccess;

@SuppressWarnings("all")
public class RefDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RefDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RefDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RefDslPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case RefDslPackage.AUTHORIZATION_RULE:
				sequence_AuthorizationRule(context, (AuthorizationRule) semanticObject); 
				return; 
			case RefDslPackage.AUTOMATION_RULE:
				sequence_AutomationRule(context, (AutomationRule) semanticObject); 
				return; 
			case RefDslPackage.FEEDBACK_DEFINITION:
				sequence_FeedbackDefinition(context, (FeedbackDefinition) semanticObject); 
				return; 
			case RefDslPackage.FEEDBACK_TYPE:
				sequence_FeedbackType(context, (FeedbackType) semanticObject); 
				return; 
			case RefDslPackage.REF_MODEL:
				sequence_RefModel(context, (RefModel) semanticObject); 
				return; 
			case RefDslPackage.RESOURCE_TYPE:
				sequence_ResourceType(context, (ResourceType) semanticObject); 
				return; 
			case RefDslPackage.USER_TYPE:
				sequence_UserType(context, (UserType) semanticObject); 
				return; 
			case RefDslPackage.VALIDATION_RULE:
				sequence_ValidationRule(context, (ValidationRule) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (name=EString type=PrimitiveType)
	 * </pre>
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RefDslPackage.Literals.ATTRIBUTE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RefDslPackage.Literals.ATTRIBUTE__NAME));
			if (transientValues.isValueTransient(semanticObject, RefDslPackage.Literals.ATTRIBUTE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RefDslPackage.Literals.ATTRIBUTE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributeAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAttributeAccess().getTypePrimitiveTypeEnumRuleCall_3_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AuthorizationRule returns AuthorizationRule
	 *
	 * Constraint:
	 *     (allowedAction=ActionKind role=[UserType|EString])
	 * </pre>
	 */
	protected void sequence_AuthorizationRule(ISerializationContext context, AuthorizationRule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RefDslPackage.Literals.AUTHORIZATION_RULE__ALLOWED_ACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RefDslPackage.Literals.AUTHORIZATION_RULE__ALLOWED_ACTION));
			if (transientValues.isValueTransient(semanticObject, RefDslPackage.Literals.AUTHORIZATION_RULE__ROLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RefDslPackage.Literals.AUTHORIZATION_RULE__ROLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAuthorizationRuleAccess().getAllowedActionActionKindEnumRuleCall_2_0(), semanticObject.getAllowedAction());
		feeder.accept(grammarAccess.getAuthorizationRuleAccess().getRoleUserTypeEStringParserRuleCall_4_0_1(), semanticObject.eGet(RefDslPackage.Literals.AUTHORIZATION_RULE__ROLE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AutomationRule returns AutomationRule
	 *
	 * Constraint:
	 *     (name=EString trigger=EString? condition=EString? actionDescription=EString?)
	 * </pre>
	 */
	protected void sequence_AutomationRule(ISerializationContext context, AutomationRule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FeedbackDefinition returns FeedbackDefinition
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         type=[FeedbackType|EString] 
	 *         subject=[ResourceType|EString] 
	 *         (writers+=[UserType|EString] writers+=[UserType|EString]*)? 
	 *         (validationRules+=ValidationRule validationRules+=ValidationRule*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_FeedbackDefinition(ISerializationContext context, FeedbackDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FeedbackType returns FeedbackType
	 *
	 * Constraint:
	 *     (name=EString hasRating=EBoolean? recursive=EBoolean? (attributes+=Attribute attributes+=Attribute*)?)
	 * </pre>
	 */
	protected void sequence_FeedbackType(ISerializationContext context, FeedbackType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RefModel returns RefModel
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (userTypes+=UserType userTypes+=UserType*)? 
	 *         (resourceTypes+=ResourceType resourceTypes+=ResourceType*)? 
	 *         (feedbackTypes+=FeedbackType feedbackTypes+=FeedbackType*)? 
	 *         (feedbackDefinitions+=FeedbackDefinition feedbackDefinitions+=FeedbackDefinition*)? 
	 *         (automationRules+=AutomationRule automationRules+=AutomationRule*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_RefModel(ISerializationContext context, RefModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ResourceType returns ResourceType
	 *
	 * Constraint:
	 *     (name=EString (attributes+=Attribute attributes+=Attribute*)? (authorizationRules+=AuthorizationRule authorizationRules+=AuthorizationRule*)?)
	 * </pre>
	 */
	protected void sequence_ResourceType(ISerializationContext context, ResourceType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UserType returns UserType
	 *
	 * Constraint:
	 *     (name=EString (superTypes+=[UserType|EString] superTypes+=[UserType|EString]*)?)
	 * </pre>
	 */
	protected void sequence_UserType(ISerializationContext context, UserType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValidationRule returns ValidationRule
	 *
	 * Constraint:
	 *     (name=EString? kind=ValidationKind implementationId=EString?)
	 * </pre>
	 */
	protected void sequence_ValidationRule(ISerializationContext context, ValidationRule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
