package pt.isep.enorm.ref.domain.enums;

/*Generated by MPS */


public enum TriggerEvent {
  ON_RESOURCE_CREATE(),
  ON_RESOURCE_UPDATE(),
  ON_RESOURCE_DELETE(),
  ON_FEEDBACK_CREATE(),
  ON_FEEDBACK_UPDATE(),
  ON_FEEDBACK_DELETE(),
  ON_REPORT_SUBMITTED(),
  ON_REPORT_THRESHOLD(),
  ON_MANUAL_REQUEST()
}
