/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import pt.isep.enorm.refdsl.refDsl.Attribute;
import pt.isep.enorm.refdsl.refDsl.AuthorizationRule;
import pt.isep.enorm.refdsl.refDsl.AutomationRule;
import pt.isep.enorm.refdsl.refDsl.FeedbackDefinition;
import pt.isep.enorm.refdsl.refDsl.FeedbackType;
import pt.isep.enorm.refdsl.refDsl.RefModel;
import pt.isep.enorm.refdsl.refDsl.ResourceType;
import pt.isep.enorm.refdsl.refDsl.UserType;

public class RefDslFormatter extends AbstractJavaFormatter {

	protected void format(RefModel refModel, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (UserType userType : refModel.getUserTypes()) {
			doc.format(userType);
		}
		for (ResourceType resourceType : refModel.getResourceTypes()) {
			doc.format(resourceType);
		}
		for (FeedbackType feedbackType : refModel.getFeedbackTypes()) {
			doc.format(feedbackType);
		}
		for (FeedbackDefinition feedbackDefinition : refModel.getFeedbackDefinitions()) {
			doc.format(feedbackDefinition);
		}
		for (AutomationRule automationRule : refModel.getAutomationRules()) {
			doc.format(automationRule);
		}
	}

	protected void format(ResourceType resourceType, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Attribute attribute : resourceType.getAttributes()) {
			doc.format(attribute);
		}
		for (AuthorizationRule authorizationRule : resourceType.getAuthorizationRules()) {
			doc.format(authorizationRule);
		}
	}
	
	// TODO: implement for FeedbackType, FeedbackDefinition
}
