package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedCommentReviewService;
import pt.isep.enorm.ref.repository.CommentReviewRepository;
import pt.isep.enorm.ref.domain.CommentReview;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;

@Service
public class CommentReviewService extends GeneratedCommentReviewService {

  private final ModerationService moderationService;

  public CommentReviewService(CommentReviewRepository feedbackRepository, ModerationService moderationServices) {
    super(feedbackRepository);
    this.moderationService = moderationServices;
  }

  @Override
  protected void afterCommentReviewCreated(CommentReview savedResource) {
    moderationService.moderateAutomatically("Resource", savedResource.getId(), TriggerEvent.ON_RESOURCE_CREATE, moderationContent(savedResource));
  }
  protected String moderationContent(CommentReview savedResource) {
    return savedResource.toString();
  }

}
