package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedProductReviewService;
import pt.isep.enorm.ref.repository.ProductReviewRepository;

@Service
public class ProductReviewService extends GeneratedProductReviewService {


  public ProductReviewService(ProductReviewRepository feedbackRepository) {
    super(feedbackRepository);
  }


}
