package pt.isep.enorm.ref.domain.value;

/*Generated by MPS */

import jakarta.persistence.Embeddable;
import jakarta.persistence.Column;

@Embeddable
public class SubredditDescription {
  @Column(name = "subreddit", nullable = false, length = 120)
  private String value;

  protected SubredditDescription() {
  }

  public String Subreddit(String value) {
    return this.value = value;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
