package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedModerationService;
import org.springframework.transaction.annotation.Transactional;
import pt.isep.enorm.ref.service.generated.projection.ModerationSimulationResult;
import pt.isep.enorm.ref.domain.UserType;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;
import java.nio.file.AccessDeniedException;
import pt.isep.enorm.ref.service.generated.GeneratedModerationModel;
import java.util.Collections;
import java.util.List;

@Service
public class ModerationService extends GeneratedModerationService {
  @Transactional
  public ModerationSimulationResult simulateModeration(UserType moderator, String targetType, Long targetId, TriggerEvent trigger, String content) throws AccessDeniedException {
    ensureModerator(moderator);
    GeneratedModerationModel.PolicySpec policy = policyFor(targetType, trigger);
    GeneratedModerationModel.AutomationRuleSpec rule = primaryRule(policy);
    if (!(triggerMatches(policy, trigger))) {
      return new ModerationSimulationResult(targetType, targetId, null, null, trigger, (policy == null ? null : policy.getMode()), decisionFor(policy, Collections.<String>emptyList()), "SKIPPED", Collections.<String>emptyList(), explanationFor(policy, rule, trigger, Collections.<String>emptyList()));
    }
    List<String> matchedKeywords = findMatchedKeywords(content, rule);
    return new ModerationSimulationResult(targetType, targetId, null, null, trigger, policy.getMode(), decisionFor(policy, matchedKeywords), statusFor(policy, rule, matchedKeywords), matchedKeywords, explanationFor(policy, rule, trigger, matchedKeywords));
  }

  @Transactional
  public ModerationSimulationResult moderateAutomatically(String targetType, Long targetId, TriggerEvent trigger, String content) {
    GeneratedModerationModel.PolicySpec policy = policyFor(targetType, trigger);
    GeneratedModerationModel.AutomationRuleSpec rule = primaryRule(policy);
    if (!(isAutomatic(policy)) || !(triggerMatches(policy, trigger))) {
      return new ModerationSimulationResult(targetType, targetId, null, null, trigger, (policy == null ? null : policy.getMode()), decisionFor(policy, List.<String>of()), "SKIPPED", List.<String>of(), explanationFor(policy, rule, trigger, List.<String>of()));
    }
    List<String> matchedKeywords = findMatchedKeywords(content, rule);
    return new ModerationSimulationResult(targetType, targetId, null, null, trigger, policy.getMode(), decisionFor(policy, matchedKeywords), statusFor(policy, rule, matchedKeywords), matchedKeywords, explanationFor(policy, rule, trigger, matchedKeywords));
  }


  private void ensureModerator(final UserType moderator) throws AccessDeniedException {
    if (moderator == null) {
      throw new IllegalArgumentException("Moderator is required.");
    }
    boolean allowed = GeneratedModerationModel.POLICIES.stream().anyMatch((policy) -> policy.getExecutedByKind() == null || policy.getExecutedByKind() == moderator.getRole());
    if (!(allowed)) {
      throw new AccessDeniedException("User is not allowed to moderate this target.");
    }
  }
}
