package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedOrderItemService;
import pt.isep.enorm.ref.repository.OrderItemRepository;
import pt.isep.enorm.ref.domain.OrderItem;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;

@Service
public class OrderItemService extends GeneratedOrderItemService {

  private final ModerationService moderationService;

  public OrderItemService(OrderItemRepository feedbackRepository, ModerationService moderationServices) {
    super(feedbackRepository);
    this.moderationService = moderationServices;
  }

  @Override
  protected void afterOrderItemCreated(OrderItem savedResource) {
    moderationService.moderateAutomatically("Resource", savedResource.getId(), TriggerEvent.ON_RESOURCE_CREATE, moderationContent(savedResource));
  }
  protected String moderationContent(OrderItem savedResource) {
    return savedResource.toString();
  }

}
