package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedComment;

@Entity(name = "Comment")
@Table(name = "comments")
public class Comment extends GeneratedComment {
}
