package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedReportOnPost;

@Entity(name = "ReportOnPost")
@Table(name = "report_on_posts")
public class ReportOnPost extends GeneratedReportOnPost {
}
