package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedVoteOnPostMediaReference;

@Entity(name = "VoteOnPostMediaReference")
@Table(name = "voteonpost_media_references")
public class VoteOnPostMediaReference extends GeneratedVoteOnPostMediaReference {
}
