package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedVoteOnCommentMediaReference;

@Entity(name = "VoteOnCommentMediaReference")
@Table(name = "voteoncomment_media_references")
public class VoteOnCommentMediaReference extends GeneratedVoteOnCommentMediaReference {
}
