package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedVoteOnPost;

@Entity(name = "VoteOnPost")
@Table(name = "vote_on_posts")
public class VoteOnPost extends GeneratedVoteOnPost {
}
