package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedAuthorizationRule;

@Entity(name = "AuthorizationRule")
@Table(name = "authorization_rules")
public class AuthorizationRule extends GeneratedAuthorizationRule {
}
