package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedContextResource;

@Entity(name = "ContextResource")
@Table(name = "context_resources")
public class ContextResource extends GeneratedContextResource {
}
