package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedProductReview;

@Entity(name = "ProductReview")
@Table(name = "product_reviews")
public class ProductReview extends GeneratedProductReview {
}
