package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedVerificationPolicy;

@Entity(name = "VerificationPolicy")
@Table(name = "verification_policys")
public class VerificationPolicy extends GeneratedVerificationPolicy {
}
