package pt.isep.enorm.ref.domain.value;

/*Generated by MPS */

import jakarta.persistence.Embeddable;
import jakarta.persistence.Column;

@Embeddable
public class ProductCreatedAt {
  @Column(name = "product", nullable = false, length = 120)
  private String value;

  protected ProductCreatedAt() {
  }

  public String Product(String value) {
    return this.value = value;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
