package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedPostService;
import pt.isep.enorm.ref.repository.PostRepository;
import pt.isep.enorm.ref.domain.Post;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;

@Service
public class PostService extends GeneratedPostService {

  private final ModerationService moderationService;

  public PostService(PostRepository feedbackRepository, ModerationService moderationServices) {
    super(feedbackRepository);
    this.moderationService = moderationServices;
  }

  @Override
  protected void afterPostCreated(Post savedResource) {
    moderationService.moderateAutomatically("Resource", savedResource.getId(), TriggerEvent.ON_RESOURCE_CREATE, moderationContent(savedResource));
  }
  protected String moderationContent(Post savedResource) {
    return savedResource.toString();
  }

}
