package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedReportOnPostService;
import pt.isep.enorm.ref.repository.ReportOnPostRepository;

@Service
public class ReportOnPostService extends GeneratedReportOnPostService {


  public ReportOnPostService(ReportOnPostRepository feedbackRepository) {
    super(feedbackRepository);
  }


}
