package pt.isep.enorm.ref.service;

/*Generated by MPS */

import org.springframework.stereotype.Service;
import pt.isep.enorm.ref.service.generated.GeneratedVoteOnCommentService;
import pt.isep.enorm.ref.repository.VoteOnCommentRepository;

@Service
public class VoteOnCommentService extends GeneratedVoteOnCommentService {


  public VoteOnCommentService(VoteOnCommentRepository feedbackRepository) {
    super(feedbackRepository);
  }


}
