package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedModerationController;
import pt.isep.enorm.ref.service.ModerationService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.http.ResponseEntity;
import pt.isep.enorm.ref.service.generated.projection.ModerationSimulationResult;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import pt.isep.enorm.ref.domain.UserType;
import org.springframework.web.bind.annotation.RequestBody;
import java.nio.file.AccessDeniedException;
import pt.isep.enorm.ref.domain.enums.TriggerEvent;

@RestController
@RequestMapping(value = "/api/moderation")
public class ModerationController extends GeneratedModerationController {
  private final ModerationService moderationService;
  public ModerationController(ModerationService moderationService) {
    super(moderationService);
    this.moderationService = moderationService;
  }
  @PostMapping(value = "/simulate")
  public ResponseEntity<ModerationSimulationResult> simulateModeration(@AuthenticationPrincipal UserType currentUser, @RequestBody ModerationSimulationRequest request) throws AccessDeniedException {
    validate(request);
    ModerationSimulationResult result = moderationService.simulateModeration(currentUser, request.getTargetType(), request.getTargetId(), request.getTrigger(), request.getContent());
    return ResponseEntity.ok(result);
  }
  private void validate(ModerationSimulationRequest request) {
    if (request == null) {
      throw new IllegalArgumentException("Moderation simulation payload is required.");
    }
    if (request.getTargetType() == null || request.getTargetType().isBlank()) {
      throw new IllegalArgumentException("Moderation targetType is required.");
    }
    if (request.getTrigger() == null) {
      throw new IllegalArgumentException("Moderation trigger is required.");
    }
  }
  public static class ModerationSimulationRequest {
    private String targetType;
    private Long targetId;
    private TriggerEvent trigger;
    private String content;
    public String getTargetType() {
      return targetType;
    }
    public void setTargetType(String targetType) {
      this.targetType = targetType;
    }
    public Long getTargetId() {
      return targetId;
    }
    public void setTargetId(Long targetId) {
      this.targetId = targetId;
    }
    public TriggerEvent getTrigger() {
      return trigger;
    }
    public void setTrigger(TriggerEvent trigger) {
      this.trigger = trigger;
    }
    public String getContent() {
      return content;
    }
    public void setContent(String content) {
      this.content = content;
    }
  }
}
