package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedOrderItemController;
import pt.isep.enorm.ref.service.OrderItemService;

@RestController
@RequestMapping(value = "/api")
public class OrderItemController extends GeneratedOrderItemController {
  public OrderItemController(OrderItemService templateService) {
    super(templateService);
  }
}
