/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import pt.isep.enorm.refdsl.refDsl.RefDslPackage;
import pt.isep.enorm.refdsl.refDsl.ValidationKind;
import pt.isep.enorm.refdsl.refDsl.ValidationRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Validation Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.impl.ValidationRuleImpl#getName <em>Name</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.impl.ValidationRuleImpl#getKind <em>Kind</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.impl.ValidationRuleImpl#getImplementationId <em>Implementation Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValidationRuleImpl extends MinimalEObjectImpl.Container implements ValidationRule
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected static final ValidationKind KIND_EDEFAULT = ValidationKind.AUTOMATIC;

  /**
   * The cached value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected ValidationKind kind = KIND_EDEFAULT;

  /**
   * The default value of the '{@link #getImplementationId() <em>Implementation Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImplementationId()
   * @generated
   * @ordered
   */
  protected static final String IMPLEMENTATION_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getImplementationId() <em>Implementation Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImplementationId()
   * @generated
   * @ordered
   */
  protected String implementationId = IMPLEMENTATION_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValidationRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RefDslPackage.Literals.VALIDATION_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RefDslPackage.VALIDATION_RULE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ValidationKind getKind()
  {
    return kind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKind(ValidationKind newKind)
  {
    ValidationKind oldKind = kind;
    kind = newKind == null ? KIND_EDEFAULT : newKind;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RefDslPackage.VALIDATION_RULE__KIND, oldKind, kind));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getImplementationId()
  {
    return implementationId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setImplementationId(String newImplementationId)
  {
    String oldImplementationId = implementationId;
    implementationId = newImplementationId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RefDslPackage.VALIDATION_RULE__IMPLEMENTATION_ID, oldImplementationId, implementationId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RefDslPackage.VALIDATION_RULE__NAME:
        return getName();
      case RefDslPackage.VALIDATION_RULE__KIND:
        return getKind();
      case RefDslPackage.VALIDATION_RULE__IMPLEMENTATION_ID:
        return getImplementationId();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RefDslPackage.VALIDATION_RULE__NAME:
        setName((String)newValue);
        return;
      case RefDslPackage.VALIDATION_RULE__KIND:
        setKind((ValidationKind)newValue);
        return;
      case RefDslPackage.VALIDATION_RULE__IMPLEMENTATION_ID:
        setImplementationId((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RefDslPackage.VALIDATION_RULE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RefDslPackage.VALIDATION_RULE__KIND:
        setKind(KIND_EDEFAULT);
        return;
      case RefDslPackage.VALIDATION_RULE__IMPLEMENTATION_ID:
        setImplementationId(IMPLEMENTATION_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RefDslPackage.VALIDATION_RULE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RefDslPackage.VALIDATION_RULE__KIND:
        return kind != KIND_EDEFAULT;
      case RefDslPackage.VALIDATION_RULE__IMPLEMENTATION_ID:
        return IMPLEMENTATION_ID_EDEFAULT == null ? implementationId != null : !IMPLEMENTATION_ID_EDEFAULT.equals(implementationId);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", kind: ");
    result.append(kind);
    result.append(", implementationId: ");
    result.append(implementationId);
    result.append(')');
    return result.toString();
  }

} //ValidationRuleImpl
