/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRefDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(pt.isep.enorm.refdsl.refDsl.RefDslPackage.eINSTANCE);
		return result;
	}
}
