package pt.isep.enorm.ref.repository;

/*Generated by MPS */

import org.springframework.stereotype.Repository;
import pt.isep.enorm.ref.repository.generated.GeneratedReportOnVideoRepository;

@Repository
public interface ReportOnVideoRepository extends GeneratedReportOnVideoRepository {
}
