/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RefDslStandaloneSetup extends RefDslStandaloneSetupGenerated {

	public static void doSetup() {
		new RefDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
