/*
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import pt.isep.enorm.refdsl.ui.internal.RefdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RefDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RefdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RefdslActivator activator = RefdslActivator.getInstance();
		return activator != null ? activator.getInjector(RefdslActivator.PT_ISEP_ENORM_REFDSL_REFDSL) : null;
	}

}
