package pt.isep.enorm.ref;

/*Generated by MPS */

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.boot.SpringApplication;

@SpringBootApplication
@EnableScheduling
public class YoutubeRefApplication {
  public static void main(String[] args) {
    SpringApplication.run(YoutubeRefApplication.class, args);
  }
}
