package pt.isep.enorm.ref.domain.value;

/*Generated by MPS */

import jakarta.persistence.Embeddable;
import jakarta.persistence.Column;

@Embeddable
public class OrderItemQuantity {
  @Column(name = "order_item", nullable = false, length = 120)
  private int value;

  protected OrderItemQuantity() {
  }

  public int OrderItem(int value) {
    return this.value = value;
  }

  public int getValue() {
    return value;
  }

  public void setValue(int value) {
    this.value = value;
  }
}
