package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedHelpfulVoteOnCommentMediaReference;

@Entity(name = "HelpfulVoteOnCommentMediaReference")
@Table(name = "helpfulvoteoncomment_media_references")
public class HelpfulVoteOnCommentMediaReference extends GeneratedHelpfulVoteOnCommentMediaReference {
}
