package pt.isep.enorm.ref.domain;

/*Generated by MPS */

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import pt.isep.enorm.ref.domain.generated.GeneratedProductReviewMediaReference;

@Entity(name = "ProductReviewMediaReference")
@Table(name = "productreview_media_references")
public class ProductReviewMediaReference extends GeneratedProductReviewMediaReference {
}
