<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ref" nsURI="http://www.example.org/ref" nsPrefix="ref">
  <eClassifiers xsi:type="ecore:EEnum" name="UserKind">
    <eLiterals name="GENERIC"/>
    <eLiterals name="BUYER" value="1"/>
    <eLiterals name="SELLER" value="2"/>
    <eLiterals name="CREATOR" value="3"/>
    <eLiterals name="MODERATOR" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContextKind">
    <eLiterals name="GLOBAL"/>
    <eLiterals name="COMMUNITY" value="1"/>
    <eLiterals name="CHANNEL" value="2"/>
    <eLiterals name="CATALOG" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="TEXT"/>
    <eLiterals name="NUMBER" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="DATE" value="3"/>
    <eLiterals name="DATETIME" value="4"/>
    <eLiterals name="IMAGE" value="5"/>
    <eLiterals name="VIDEO" value="6"/>
    <eLiterals name="URL" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackKind">
    <eLiterals name="COMMENT"/>
    <eLiterals name="REVIEW" value="1"/>
    <eLiterals name="REACTION" value="2"/>
    <eLiterals name="VOTE" value="3"/>
    <eLiterals name="REPORT" value="4"/>
    <eLiterals name="SUBSCRIPTION" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackSubjectScope">
    <eLiterals name="RESOURCE_ONLY"/>
    <eLiterals name="FEEDBACK_ONLY" value="1"/>
    <eLiterals name="RESOURCE_OR_FEEDBACK" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackPolarity">
    <eLiterals name="NONE"/>
    <eLiterals name="LIKE_DISLIKE" value="1"/>
    <eLiterals name="UP_DOWN" value="2"/>
    <eLiterals name="STARS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeedbackStatus">
    <eLiterals name="ENABLED"/>
    <eLiterals name="DISABLED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VerificationRequirement">
    <eLiterals name="NONE"/>
    <eLiterals name="OPTIONAL" value="1"/>
    <eLiterals name="REQUIRED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidationKind">
    <eLiterals name="AUTOMATIC"/>
    <eLiterals name="MANUAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RuleSeverity">
    <eLiterals name="INFO"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="ERROR" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModerationMode">
    <eLiterals name="AUTOMATIC"/>
    <eLiterals name="MANUAL" value="1"/>
    <eLiterals name="HYBRID" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModerationDecision">
    <eLiterals name="APPROVED"/>
    <eLiterals name="FLAGGED" value="1"/>
    <eLiterals name="HIDDEN" value="2"/>
    <eLiterals name="REMOVED" value="3"/>
    <eLiterals name="BLOCKED" value="4"/>
    <eLiterals name="REJECTED" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionKind">
    <eLiterals name="READ"/>
    <eLiterals name="CREATE" value="1"/>
    <eLiterals name="UPDATE" value="2"/>
    <eLiterals name="DELETE" value="3"/>
    <eLiterals name="COMMENT" value="4"/>
    <eLiterals name="RATE" value="5"/>
    <eLiterals name="VOTE" value="6"/>
    <eLiterals name="REPORT" value="7"/>
    <eLiterals name="SUBSCRIBE" value="8"/>
    <eLiterals name="MODERATE" value="9"/>
    <eLiterals name="VALIDATE" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerEvent">
    <eLiterals name="ON_RESOURCE_CREATE"/>
    <eLiterals name="ON_RESOURCE_UPDATE" value="1"/>
    <eLiterals name="ON_RESOURCE_DELETE" value="2"/>
    <eLiterals name="ON_FEEDBACK_CREATE" value="3"/>
    <eLiterals name="ON_FEEDBACK_UPDATE" value="4"/>
    <eLiterals name="ON_FEEDBACK_DELETE" value="5"/>
    <eLiterals name="ON_REPORT_SUBMITTED" value="6"/>
    <eLiterals name="ON_REPORT_THRESHOLD" value="7"/>
    <eLiterals name="ON_MANUAL_REQUEST" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConditionOperator">
    <eLiterals name="CONTAINS_KEYWORDS"/>
    <eLiterals name="NOT_CONTAINS_KEYWORDS" value="1"/>
    <eLiterals name="MATCH_REGEX" value="2"/>
    <eLiterals name="NOT_MATCH_REGEX" value="3"/>
    <eLiterals name="HAS_PROPERTY" value="4"/>
    <eLiterals name="NOT_HAS_PROPERTY" value="5"/>
    <eLiterals name="HAS_SPECIFIC_PROPERTY" value="6"/>
    <eLiterals name="NOT_HAS_SPECIFIC_PROPERTY" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionResultKind">
    <eLiterals name="DISPLAY_MESSAGE"/>
    <eLiterals name="FLAG_CONTENT" value="1"/>
    <eLiterals name="HIDE_CONTENT" value="2"/>
    <eLiterals name="REMOVE_CONTENT" value="3"/>
    <eLiterals name="BLOCK_SUBMISSION" value="4"/>
    <eLiterals name="NOTIFY_MODERATOR" value="5"/>
    <eLiterals name="AUTO_APPROVE" value="6"/>
    <eLiterals name="AUTO_REJECT" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SortCriterion">
    <eLiterals name="DATE"/>
    <eLiterals name="VALUE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SortDirection">
    <eLiterals name="ASC"/>
    <eLiterals name="DESC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userTypes" upperBound="-1"
        eType="#//UserType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceTypes" upperBound="-1"
        eType="#//ResourceType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextTypes" upperBound="-1"
        eType="#//ContextType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRelations" upperBound="-1"
        eType="#//ResourceRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedbackTypes" upperBound="-1"
        eType="#//FeedbackType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedbackDefinitions" upperBound="-1"
        eType="#//FeedbackDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorizationRules" upperBound="-1"
        eType="#//AuthorizationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationRules" upperBound="-1"
        eType="#//ValidationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moderationPolicies" upperBound="-1"
        eType="#//ModerationPolicy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="automationRules" upperBound="-1"
        eType="#//AutomationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationPolicies" upperBound="-1"
        eType="#//VerificationPolicy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortingPolicies" upperBound="-1"
        eType="#//SortingPolicy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//UserKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//UserType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ContextKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//ResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportsMedia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PrimitiveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiValued" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recursive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//FeedbackKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subjectScope" eType="#//FeedbackSubjectScope"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasRating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recursive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowsText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowsMedia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//FeedbackPolarity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//FeedbackStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RatingPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeedbackDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresVerifiedContext"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verificationRequirement"
        eType="#//VerificationRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniquePerAuthorTarget"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//FeedbackType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjectResource" eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//UserType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjectFeedback" eType="#//FeedbackDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" eType="#//FeedbackPolicy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rating" eType="#//RatingPolicy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ValidationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//RuleSeverity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesToResource" eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesToFeedback" eType="#//FeedbackDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedBy" eType="#//AutomationRule"
        eOpposite="#//AutomationRule/invokedValidationRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModerationPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//ModerationMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" eType="#//TriggerEvent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decision" eType="#//ModerationDecision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorsResource" lowerBound="1"
        eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorsFeedback" lowerBound="1"
        eType="#//FeedbackDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedBy" lowerBound="1"
        eType="#//UserType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContext" eType="#//ContextType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthorizationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowedAction" eType="#//ActionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="#//UserType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ContextType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceTarget" lowerBound="1"
        eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedbackTarget" eType="#//FeedbackDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" eType="#//TriggerEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContext" eType="#//ContextType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onFeedback" lowerBound="1"
        eType="#//FeedbackDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" lowerBound="1" eType="#//ValidationRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedValidationRules"
        upperBound="-1" eType="#//ValidationRule" eOpposite="#//ValidationRule/invokedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        upperBound="-1" eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ConditionOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ConditionValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ActionResultKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerificationPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//ValidationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliesWhen" eType="#//TriggerEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verifies" lowerBound="1"
        eType="#//FeedbackDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criterion" eType="#//SortCriterion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//SortDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesToResource" eType="#//ResourceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesToFeedback" eType="#//FeedbackDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContext" eType="#//ContextType"/>
  </eClassifiers>
</ecore:EPackage>
