package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedCommentReviewController;
import pt.isep.enorm.ref.service.CommentReviewService;

@RestController
@RequestMapping(value = "/api")
public class CommentReviewController extends GeneratedCommentReviewController {
  public CommentReviewController(CommentReviewService templateService) {
    super(templateService);
  }
}
