package pt.isep.enorm.ref.web;

/*Generated by MPS */

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import pt.isep.enorm.ref.web.generated.GeneratedPolicyController;
import pt.isep.enorm.ref.service.PolicyService;

@RestController
@RequestMapping(value = "/api")
public class PolicyController extends GeneratedPolicyController {
  public PolicyController(PolicyService templateService) {
    super(templateService);
  }
}
