package pt.isep.enorm.ref.domain.enums;

/*Generated by MPS */


public enum ActionKind {
  READ(),
  CREATE(),
  UPDATE(),
  DELETE(),
  COMMENT(),
  RATE(),
  VOTE(),
  REPORT(),
  SUBSCRIBE(),
  MODERATE(),
  VALIDATE()
}
