package pt.isep.enorm.ref.domain.enums;

/*Generated by MPS */


public enum ActionResultKind {
  DISPLAY_MESSAGE(),
  FLAG_CONTENT(),
  HIDE_CONTENT(),
  REMOVE_CONTENT(),
  BLOCK_SUBMISSION(),
  NOTIFY_MODERATOR(),
  AUTO_APPROVE(),
  AUTO_REJECT()
}
