/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Authorization Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AuthorizationRule#getAllowedAction <em>Allowed Action</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AuthorizationRule#getRole <em>Role</em>}</li>
 * </ul>
 *
 * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAuthorizationRule()
 * @model
 * @generated
 */
public interface AuthorizationRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Allowed Action</b></em>' attribute.
   * The literals are from the enumeration {@link pt.isep.enorm.refdsl.refDsl.ActionKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allowed Action</em>' attribute.
   * @see pt.isep.enorm.refdsl.refDsl.ActionKind
   * @see #setAllowedAction(ActionKind)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAuthorizationRule_AllowedAction()
   * @model
   * @generated
   */
  ActionKind getAllowedAction();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AuthorizationRule#getAllowedAction <em>Allowed Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allowed Action</em>' attribute.
   * @see pt.isep.enorm.refdsl.refDsl.ActionKind
   * @see #getAllowedAction()
   * @generated
   */
  void setAllowedAction(ActionKind value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' reference.
   * @see #setRole(UserType)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAuthorizationRule_Role()
   * @model
   * @generated
   */
  UserType getRole();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AuthorizationRule#getRole <em>Role</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' reference.
   * @see #getRole()
   * @generated
   */
  void setRole(UserType value);

} // AuthorizationRule
