/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Automation Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getName <em>Name</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getContext <em>Context</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getInContext <em>In Context</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getOnFeedback <em>On Feedback</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getUses <em>Uses</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getInvokedValidationRules <em>Invoked Validation Rules</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getConditions <em>Conditions</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule()
 * @model
 * @generated
 */
public interface AutomationRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' attribute.
   * The literals are from the enumeration {@link pt.isep.enorm.refdsl.refDsl.TriggerEvent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' attribute.
   * @see pt.isep.enorm.refdsl.refDsl.TriggerEvent
   * @see #setTrigger(TriggerEvent)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_Trigger()
   * @model
   * @generated
   */
  TriggerEvent getTrigger();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getTrigger <em>Trigger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' attribute.
   * @see pt.isep.enorm.refdsl.refDsl.TriggerEvent
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(TriggerEvent value);

  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(ResourceType)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_Context()
   * @model
   * @generated
   */
  ResourceType getContext();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(ResourceType value);

  /**
   * Returns the value of the '<em><b>In Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Context</em>' reference.
   * @see #setInContext(ContextType)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_InContext()
   * @model
   * @generated
   */
  ContextType getInContext();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getInContext <em>In Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In Context</em>' reference.
   * @see #getInContext()
   * @generated
   */
  void setInContext(ContextType value);

  /**
   * Returns the value of the '<em><b>On Feedback</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Feedback</em>' reference.
   * @see #setOnFeedback(FeedbackDefinition)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_OnFeedback()
   * @model
   * @generated
   */
  FeedbackDefinition getOnFeedback();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getOnFeedback <em>On Feedback</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Feedback</em>' reference.
   * @see #getOnFeedback()
   * @generated
   */
  void setOnFeedback(FeedbackDefinition value);

  /**
   * Returns the value of the '<em><b>Uses</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uses</em>' reference.
   * @see #setUses(ValidationRule)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_Uses()
   * @model
   * @generated
   */
  ValidationRule getUses();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.AutomationRule#getUses <em>Uses</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uses</em>' reference.
   * @see #getUses()
   * @generated
   */
  void setUses(ValidationRule value);

  /**
   * Returns the value of the '<em><b>Invoked Validation Rules</b></em>' reference list.
   * The list contents are of type {@link pt.isep.enorm.refdsl.refDsl.ValidationRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invoked Validation Rules</em>' reference list.
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_InvokedValidationRules()
   * @model
   * @generated
   */
  EList<ValidationRule> getInvokedValidationRules();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link pt.isep.enorm.refdsl.refDsl.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link pt.isep.enorm.refdsl.refDsl.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getAutomationRule_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

} // AutomationRule
