/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feedback Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#getName <em>Name</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#isHasRating <em>Has Rating</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#isRecursive <em>Recursive</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getFeedbackType()
 * @model
 * @generated
 */
public interface FeedbackType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getFeedbackType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Has Rating</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Rating</em>' attribute.
   * @see #setHasRating(boolean)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getFeedbackType_HasRating()
   * @model
   * @generated
   */
  boolean isHasRating();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#isHasRating <em>Has Rating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Rating</em>' attribute.
   * @see #isHasRating()
   * @generated
   */
  void setHasRating(boolean value);

  /**
   * Returns the value of the '<em><b>Recursive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recursive</em>' attribute.
   * @see #setRecursive(boolean)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getFeedbackType_Recursive()
   * @model
   * @generated
   */
  boolean isRecursive();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.FeedbackType#isRecursive <em>Recursive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recursive</em>' attribute.
   * @see #isRecursive()
   * @generated
   */
  void setRecursive(boolean value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link pt.isep.enorm.refdsl.refDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getFeedbackType_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // FeedbackType
