/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage
 * @generated
 */
public interface RefDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RefDslFactory eINSTANCE = pt.isep.enorm.refdsl.refDsl.impl.RefDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Ref Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ref Model</em>'.
   * @generated
   */
  RefModel createRefModel();

  /**
   * Returns a new object of class '<em>User Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Type</em>'.
   * @generated
   */
  UserType createUserType();

  /**
   * Returns a new object of class '<em>Resource Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resource Type</em>'.
   * @generated
   */
  ResourceType createResourceType();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Feedback Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Feedback Type</em>'.
   * @generated
   */
  FeedbackType createFeedbackType();

  /**
   * Returns a new object of class '<em>Feedback Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Feedback Definition</em>'.
   * @generated
   */
  FeedbackDefinition createFeedbackDefinition();

  /**
   * Returns a new object of class '<em>Validation Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Validation Rule</em>'.
   * @generated
   */
  ValidationRule createValidationRule();

  /**
   * Returns a new object of class '<em>Authorization Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Authorization Rule</em>'.
   * @generated
   */
  AuthorizationRule createAuthorizationRule();

  /**
   * Returns a new object of class '<em>Automation Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Automation Rule</em>'.
   * @generated
   */
  AutomationRule createAutomationRule();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RefDslPackage getRefDslPackage();

} //RefDslFactory
