/**
 * generated by Xtext 2.42.0
 */
package pt.isep.enorm.refdsl.refDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.ResourceType#getName <em>Name</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.ResourceType#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link pt.isep.enorm.refdsl.refDsl.ResourceType#getAuthorizationRules <em>Authorization Rules</em>}</li>
 * </ul>
 *
 * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getResourceType()
 * @model
 * @generated
 */
public interface ResourceType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getResourceType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link pt.isep.enorm.refdsl.refDsl.ResourceType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link pt.isep.enorm.refdsl.refDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getResourceType_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Authorization Rules</b></em>' containment reference list.
   * The list contents are of type {@link pt.isep.enorm.refdsl.refDsl.AuthorizationRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authorization Rules</em>' containment reference list.
   * @see pt.isep.enorm.refdsl.refDsl.RefDslPackage#getResourceType_AuthorizationRules()
   * @model containment="true"
   * @generated
   */
  EList<AuthorizationRule> getAuthorizationRules();

} // ResourceType
