package pt.isep.enorm.ref.domain.value;

/*Generated by MPS */

import jakarta.persistence.Embeddable;
import jakarta.persistence.Column;

@Embeddable
public class ChannelDescription {
  @Column(name = "channel", nullable = false, length = 120)
  private String value;

  protected ChannelDescription() {
  }

  public String Channel(String value) {
    return this.value = value;
  }

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
